from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class StrategyValueDoctrine:
    value: str
    short_label: str
    behavioral_meaning: str
    target_user_effect: str
    positive_instructions: tuple[str, ...]
    negative_instructions: tuple[str, ...]
    response_shape_guidance: tuple[str, ...]
    grounding_tool_implications: tuple[str, ...]
    compatibility_notes: tuple[str, ...] = ()
    model_summary_en: str = ""
    model_summary_zh: str = ""


@dataclass(frozen=True)
class StrategyTermDefinition:
    term: str
    family: str
    exposure_class: str
    runtime_owner: str
    values: dict[str, StrategyValueDoctrine] = field(default_factory=dict)
    internal_only: bool = False
    notes: tuple[str, ...] = ()

    def get(self, value: Any) -> StrategyValueDoctrine | None:
        normalized = str(value or "").strip()
        if not normalized:
            return None
        return self.values.get(normalized)


def _value(
    value: str,
    *,
    short_label: str,
    behavioral_meaning: str,
    target_user_effect: str,
    positive_instructions: tuple[str, ...],
    negative_instructions: tuple[str, ...],
    response_shape_guidance: tuple[str, ...],
    grounding_tool_implications: tuple[str, ...],
    compatibility_notes: tuple[str, ...] = (),
    model_summary_en: str,
    model_summary_zh: str,
) -> StrategyValueDoctrine:
    return StrategyValueDoctrine(
        value=value,
        short_label=short_label,
        behavioral_meaning=behavioral_meaning,
        target_user_effect=target_user_effect,
        positive_instructions=positive_instructions,
        negative_instructions=negative_instructions,
        response_shape_guidance=response_shape_guidance,
        grounding_tool_implications=grounding_tool_implications,
        compatibility_notes=compatibility_notes,
        model_summary_en=model_summary_en,
        model_summary_zh=model_summary_zh,
    )


TERM_DEFINITIONS: dict[str, StrategyTermDefinition] = {
    "primary_residual": StrategyTermDefinition(
        term="primary_residual",
        family="decision",
        exposure_class="mixed",
        runtime_owner="residual_diagnosis",
        values={
            "R_e": _value(
                "R_e",
                short_label="cognitive",
                behavioral_meaning="The main bottleneck is understanding, concept calibration, or explanation quality.",
                target_user_effect="The user should leave with a clearer mental model and less conceptual confusion.",
                positive_instructions=(
                    "Ground explanations in the user's materials or concrete evidence when available.",
                    "Slow the response down into concept repair, not hype or pressure.",
                ),
                negative_instructions=(
                    "Do not jump straight to motivation or behavioral pressure.",
                    "Do not answer as if the issue were value conflict or identity collapse.",
                ),
                response_shape_guidance=(
                    "Explain the key point, then give one concrete application or next move.",
                ),
                grounding_tool_implications=(
                    "Prefer retrieval and evidence-backed explanation before generic advice.",
                ),
                model_summary_en="Treat this as an understanding problem: repair the concept, ground it in the user's evidence, and avoid pushing behavior before the idea is clear.",
                model_summary_zh="把这轮当成理解修复问题：先校准概念并尽量落到用户材料，再给下一步，不要在概念还没清楚时先施加推进压力。",
            ),
            "R_n": _value(
                "R_n",
                short_label="normative",
                behavioral_meaning="The main bottleneck is judgment, criteria-building, or tradeoff navigation.",
                target_user_effect="The user should gain clearer criteria and better judgment without false certainty.",
                positive_instructions=(
                    "Surface criteria, tradeoffs, and value-sensitive constraints.",
                    "Name uncertainty instead of pretending the choice is obvious.",
                ),
                negative_instructions=(
                    "Do not collapse the decision into a single prescriptive answer too early.",
                    "Do not answer like a concept explainer if the real issue is choosing.",
                ),
                response_shape_guidance=(
                    "Offer criteria, tradeoffs, and a recommendation only with stated limits.",
                ),
                grounding_tool_implications=(
                    "Ground in the user's values, constraints, and consequences rather than general slogans.",
                ),
                model_summary_en="Treat this as a judgment problem: help the user compare criteria and tradeoffs, and avoid fake certainty.",
                model_summary_zh="把这轮当成判断问题：帮用户搭建标准与取舍，必要时给建议，但不要假装结论毫无不确定性。",
            ),
            "R_c": _value(
                "R_c",
                short_label="control",
                behavioral_meaning="The main bottleneck is execution friction, overload, or inability to convert intention into action.",
                target_user_effect="The user should regain control over the next move without being overloaded.",
                positive_instructions=(
                    "Reduce friction and convert the turn into a concrete next step.",
                    "Adjust scope and pressure to current capacity.",
                ),
                negative_instructions=(
                    "Do not give an overbuilt plan when the user cannot even start.",
                    "Do not moralize the user's difficulty.",
                ),
                response_shape_guidance=(
                    "Shrink scope, name the next move, and define what to do if it still feels too heavy.",
                ),
                grounding_tool_implications=(
                    "Prefer bounded, reversible adjustments over ambitious multi-step structures.",
                ),
                model_summary_en="Treat this as an execution-control problem: lower friction, narrow scope, and help the user restart with a realistic next move.",
                model_summary_zh="把这轮当成执行控制问题：先降阻、缩范围、减压力，帮助用户用现实可做的下一步重新启动。",
            ),
            "R_i": _value(
                "R_i",
                short_label="identity",
                behavioral_meaning="The main bottleneck is a fragile self-story or identity-level interpretation of the problem.",
                target_user_effect="The user should separate the situation from a damaging identity conclusion.",
                positive_instructions=(
                    "Re-anchor in evidence and trajectory instead of identity fusion.",
                    "Preserve agency without endorsing self-negating narratives.",
                ),
                negative_instructions=(
                    "Do not reinforce shame or destiny language.",
                    "Do not stay purely tactical if the user is attacking their own identity.",
                ),
                response_shape_guidance=(
                    "Reframe the meaning of the evidence, then give a gentle next step.",
                ),
                grounding_tool_implications=(
                    "Use concrete evidence and trajectory to loosen identity collapse.",
                ),
                model_summary_en="Treat this as an identity-fragile turn: separate evidence from self-judgment and help the user regain a steadier frame.",
                model_summary_zh="把这轮当成身份脆弱回合：把证据和自我否定分开，先稳住解释框架，再给轻一点的下一步。",
            ),
            "R_mixed": _value(
                "R_mixed",
                short_label="mixed",
                behavioral_meaning="The turn has multiple plausible bottlenecks and needs a cautious, clarifying posture.",
                target_user_effect="The user should get a safer first move while ambiguity stays visible.",
                positive_instructions=(
                    "Acknowledge ambiguity and avoid overcommitting to one theory.",
                    "Prefer a clarifying or diagnostic move first.",
                ),
                negative_instructions=(
                    "Do not act as if one diagnosis is already certain.",
                ),
                response_shape_guidance=(
                    "Name the likely forks and choose the safest next move.",
                ),
                grounding_tool_implications=(
                    "Use light, reversible actions until the main bottleneck is clearer.",
                ),
                model_summary_en="Multiple bottlenecks are plausible here, so keep the move cautious, explicit, and reversible.",
                model_summary_zh="这里可能不止一个真实瓶颈，所以先用更谨慎、显式、可逆的方式推进，不要过早下死判断。",
            ),
            "R_unknown": _value(
                "R_unknown",
                short_label="unknown",
                behavioral_meaning="The runtime does not yet have enough signal to act strongly.",
                target_user_effect="The user should face one useful clarification instead of a guessed solution.",
                positive_instructions=(
                    "Ask the highest-value question before committing.",
                ),
                negative_instructions=(
                    "Do not invent hidden certainty.",
                ),
                response_shape_guidance=(
                    "Ask one targeted question and hold scope until it is answered.",
                ),
                grounding_tool_implications=(
                    "Delay strong planning or diagnosis until the missing fact is known.",
                ),
                model_summary_en="Signal is weak. Ask one high-value clarifying question before acting strongly.",
                model_summary_zh="当前信号不足。先问一个高价值澄清问题，再决定是否展开更强动作。",
            ),
        },
    ),
    "loop_type": StrategyTermDefinition(
        term="loop_type",
        family="decision",
        exposure_class="mixed",
        runtime_owner="residual_diagnosis",
        values={
            "truth_seeking": _value(
                "truth_seeking",
                short_label="truth-seeking",
                behavioral_meaning="The user mainly needs the world or concept made clearer.",
                target_user_effect="The response should reduce confusion and improve truth-tracking.",
                positive_instructions=("Optimize for evidence, explanation, and conceptual precision.",),
                negative_instructions=("Do not treat this primarily as a values-choice problem.",),
                response_shape_guidance=("Lead with explanation or evidence-backed diagnosis.",),
                grounding_tool_implications=("Ground in user materials or facts before opinions.",),
                model_summary_en="This turn is truth-seeking: make reality clearer and let evidence lead.",
                model_summary_zh="这轮是求真型任务：优先把事实与概念讲清楚，让证据先行。",
            ),
            "normative": _value(
                "normative",
                short_label="normative",
                behavioral_meaning="The user mainly needs criteria and value-sensitive judgment.",
                target_user_effect="The response should improve judgment quality rather than only explain facts.",
                positive_instructions=("Make tradeoffs and decision criteria explicit.",),
                negative_instructions=("Do not hide uncertainty behind confident phrasing.",),
                response_shape_guidance=("Structure the reply around criteria, consequences, and bounded guidance.",),
                grounding_tool_implications=("Use user constraints and values as first-class evidence.",),
                model_summary_en="This turn is normative: build judgment with criteria and tradeoffs, not fake certainty.",
                model_summary_zh="这轮是规范判断型任务：围绕标准与取舍来帮助判断，而不是用自信语气掩盖不确定性。",
            ),
            "identity_repair": _value(
                "identity_repair",
                short_label="identity-repair",
                behavioral_meaning="The user needs meaning repair before a tactical answer can land cleanly.",
                target_user_effect="The response should preserve dignity and agency while staying evidence-based.",
                positive_instructions=("Repair the meaning frame before escalating tactics.",),
                negative_instructions=("Do not let the reply reinforce self-negating identity stories.",),
                response_shape_guidance=("Reframe the evidence, then offer a gentle next move.",),
                grounding_tool_implications=("Use trajectory evidence to stabilize interpretation.",),
                model_summary_en="This turn needs identity repair: fix the meaning frame before tactics.",
                model_summary_zh="这轮需要身份修复：先修正意义框架，再谈战术动作。",
            ),
        },
    ),
    "confidence_label": StrategyTermDefinition(
        term="confidence_label",
        family="decision",
        exposure_class="mixed",
        runtime_owner="residual_diagnosis",
        values={
            "high": _value(
                "high",
                short_label="high confidence",
                behavioral_meaning="The runtime has enough supporting evidence to act with more specificity.",
                target_user_effect="The response can be more direct while staying grounded.",
                positive_instructions=("Be direct, but keep the rationale visible.",),
                negative_instructions=("Do not use confidence as a reason to skip evidence.",),
                response_shape_guidance=("Give a clear direction with reasons.",),
                grounding_tool_implications=("Still cite the evidence basis when relevant.",),
                model_summary_en="Confidence is high enough for direct guidance, but keep the evidence trail visible.",
                model_summary_zh="当前把握较高，可以更直接给方向，但仍要让依据可见。",
            ),
            "medium": _value(
                "medium",
                short_label="medium confidence",
                behavioral_meaning="The runtime sees a plausible direction but should keep alternatives visible.",
                target_user_effect="The response should be useful without overstating certainty.",
                positive_instructions=("State the likely path and its limits.",),
                negative_instructions=("Do not sound absolute.",),
                response_shape_guidance=("Give a useful recommendation plus one caveat.",),
                grounding_tool_implications=("Keep contingency visible.",),
                model_summary_en="Confidence is moderate: be useful, but keep limits and alternatives explicit.",
                model_summary_zh="当前把握中等：可以给出有用方向，但要把限制和替代路径说清楚。",
            ),
            "low": _value(
                "low",
                short_label="low confidence",
                behavioral_meaning="The runtime should stay cautious and prefer clarification or provisional guidance.",
                target_user_effect="The user should see honesty about uncertainty instead of brittle advice.",
                positive_instructions=("Prefer clarification, provisional wording, or narrowed scope.",),
                negative_instructions=("Do not overcommit.",),
                response_shape_guidance=("Use lightweight, revisable guidance.",),
                grounding_tool_implications=("Treat missing information as active constraints.",),
                model_summary_en="Confidence is low: keep the move cautious, provisional, and easy to revise.",
                model_summary_zh="当前把握较低：用更谨慎、暂定、易于修正的方式推进。",
            ),
        },
    ),
    "planning_readiness": StrategyTermDefinition(
        term="planning_readiness",
        family="planning",
        exposure_class="mixed",
        runtime_owner="phase_a_insight_engine",
        values={
            "low": _value(
                "low",
                short_label="low readiness",
                behavioral_meaning="Planning should not expand until key unknowns are resolved.",
                target_user_effect="The user gets a blocker-clearing move instead of a fake plan.",
                positive_instructions=("Hold back on broad planning and surface the blocker.",),
                negative_instructions=("Do not produce a confident multi-step plan.",),
                response_shape_guidance=("Ask one high-value question or give one micro-step only.",),
                grounding_tool_implications=("Missing facts are active constraints.",),
                model_summary_en="Planning readiness is low: do not expand into a real plan until the blocker is cleared.",
                model_summary_zh="当前规划就绪度低：在关键阻塞未补齐前，不要展开成完整计划。",
            ),
            "medium": _value(
                "medium",
                short_label="medium readiness",
                behavioral_meaning="The reply can offer a provisional structure, but assumptions must stay visible.",
                target_user_effect="The user gets useful momentum without false completeness.",
                positive_instructions=("Offer a narrowed provisional path with assumptions.",),
                negative_instructions=("Do not present provisional structure as settled fact.",),
                response_shape_guidance=("State assumptions, then give a narrower plan.",),
                grounding_tool_implications=("Call out the missing pieces that would change the plan.",),
                model_summary_en="Planning readiness is medium: a provisional plan is okay, but assumptions must be explicit.",
                model_summary_zh="当前规划就绪度中等：可以先给暂定方案，但关键假设必须显式说出来。",
            ),
            "high": _value(
                "high",
                short_label="high readiness",
                behavioral_meaning="The runtime has enough structure to support a fuller plan.",
                target_user_effect="The user gets a real plan that still respects constraints and evidence.",
                positive_instructions=("Provide a fuller structure with clear sequencing and grounding.",),
                negative_instructions=("Do not confuse high readiness with permission to ignore evidence.",),
                response_shape_guidance=("Deliver a real plan with explicit sections.",),
                grounding_tool_implications=("Use materials and constraints if required.",),
                model_summary_en="Planning readiness is high enough for a fuller plan, but the plan still has to honor evidence and constraints.",
                model_summary_zh="当前规划就绪度足以支持更完整的计划，但仍要严格尊重证据与约束。",
            ),
        },
    ),
    "planning_readiness_action": StrategyTermDefinition(
        term="planning_readiness_action",
        family="planning",
        exposure_class="mixed",
        runtime_owner="phase_a_insight_engine",
        values={
            "ask": _value(
                "ask",
                short_label="ask first",
                behavioral_meaning="The next best move is a clarification before planning.",
                target_user_effect="The user answers one blocker-clearing question instead of receiving noise.",
                positive_instructions=("Ask one highest-value question before planning.",),
                negative_instructions=("Do not generate a multi-step plan first.",),
                response_shape_guidance=("One question, one reason, and hold scope.",),
                grounding_tool_implications=("Missing information outranks plan elaboration.",),
                model_summary_en="Ask first: get the missing fact before offering a real plan.",
                model_summary_zh="先问再规划：先拿到关键缺失信息，再决定是否给真实计划。",
            ),
            "provisional": _value(
                "provisional",
                short_label="provisional plan",
                behavioral_meaning="A temporary plan is allowed if it stays assumption-aware and narrow.",
                target_user_effect="The user gets direction without mistaking it for certainty.",
                positive_instructions=("Name assumptions and keep the horizon narrower.",),
                negative_instructions=("Do not present a provisional plan as final.",),
                response_shape_guidance=("Assumptions first, then a reduced-scope plan.",),
                grounding_tool_implications=("Show what new evidence would change the plan.",),
                model_summary_en="A provisional plan is allowed, but it must stay narrow and explicit about assumptions.",
                model_summary_zh="可以先给暂定计划，但必须缩范围，并把假设说清楚。",
            ),
            "proceed": _value(
                "proceed",
                short_label="proceed",
                behavioral_meaning="The runtime is cleared to deliver the appropriate planning depth for this turn.",
                target_user_effect="The user receives a meaningful plan instead of unnecessary hesitation.",
                positive_instructions=("Proceed with the compiled planning mode.",),
                negative_instructions=("Do not insert fake uncertainty if the brief is sufficient.",),
                response_shape_guidance=("Give the plan that matches the compiled contract.",),
                grounding_tool_implications=("Still obey grounding and scope constraints.",),
                model_summary_en="Proceed: the system has enough signal to give the compiled planning response.",
                model_summary_zh="可以推进：当前信号足以支撑按编译后的策略给出相应计划。",
            ),
        },
    ),
    "experience_mode": StrategyTermDefinition(
        term="experience_mode",
        family="decision_policy",
        exposure_class="model_facing",
        runtime_owner="decision_policy",
        values={
            "clarify": _value(
                "clarify",
                short_label="clarify",
                behavioral_meaning="The response should resolve one blocker before expanding scope.",
                target_user_effect="The user gives the missing fact or gets one blocker-clearing micro-step.",
                positive_instructions=("Ask one high-value question before planning or advising broadly.",),
                negative_instructions=("Do not deliver a full plan or broad answer first.",),
                response_shape_guidance=("One targeted question, optionally one micro-step, then stop.",),
                grounding_tool_implications=("Clarification outranks plan expansion.",),
                model_summary_en="Clarify mode: ask one high-value question before expanding into a plan or large answer.",
                model_summary_zh="澄清模式：先问一个高价值问题，再决定是否展开成计划或更大回答。",
            ),
            "explain": _value(
                "explain",
                short_label="explain",
                behavioral_meaning="The response should repair understanding and clarify the concept path.",
                target_user_effect="The user understands the idea better and can act on it.",
                positive_instructions=("Explain step by step and anchor in the user's materials when available.",),
                negative_instructions=("Do not replace explanation with generic motivation.",),
                response_shape_guidance=("Concept repair first, next move second.",),
                grounding_tool_implications=("Prefer grounded retrieval and explicit evidence.",),
                model_summary_en="Explain mode: repair understanding, preferably using the user's materials, before moving on.",
                model_summary_zh="解释模式：先修复理解，最好用用户材料落地，再给下一步。",
            ),
            "review": _value(
                "review",
                short_label="review",
                behavioral_meaning="The response should compare what was tried, what worked, and what needs adjustment.",
                target_user_effect="The user sees the trajectory clearly and gets a better adjusted path.",
                positive_instructions=("Audit the previous path and adapt it deliberately.",),
                negative_instructions=("Do not pretend the previous intervention is irrelevant.",),
                response_shape_guidance=("What changed, what did not, and what to adjust next.",),
                grounding_tool_implications=("Use prior intervention outcomes as evidence.",),
                model_summary_en="Review mode: examine the trajectory, identify what changed, and adapt deliberately.",
                model_summary_zh="复盘模式：回看轨迹，区分哪些生效了、哪些没生效，再做针对性调整。",
            ),
            "stabilize": _value(
                "stabilize",
                short_label="stabilize",
                behavioral_meaning="The response should reduce load, lower intensity, and help the user regain control.",
                target_user_effect="The user feels less overloaded and more able to begin.",
                positive_instructions=("Shrink scope, reduce pressure, and keep the move easy to accept.",),
                negative_instructions=("Do not push intensity, guilt, or an ambitious multi-step agenda.",),
                response_shape_guidance=("A small, low-pressure move with an easy fallback.",),
                grounding_tool_implications=("Favor session-scoped reversible adjustments.",),
                model_summary_en="Stabilize mode: reduce load, lower pressure, and help the user regain control before pushing progress.",
                model_summary_zh="稳定模式：先降负荷、降压力、帮用户重新拿回控制感，再谈推进。",
            ),
            "mobilize": _value(
                "mobilize",
                short_label="mobilize",
                behavioral_meaning="The response should convert intention into an immediately actionable next move.",
                target_user_effect="The user starts instead of circling.",
                positive_instructions=("Turn the turn into a crisp, concrete next move.",),
                negative_instructions=("Do not over-explain if the user mainly needs ignition.",),
                response_shape_guidance=("Direct next step plus a small adaptation cue.",),
                grounding_tool_implications=("Use scaffolding, not pressure spikes.",),
                model_summary_en="Mobilize mode: convert intention into a crisp next move without overbuilding the reply.",
                model_summary_zh="启动模式：把意图转成清晰可做的下一步，不要把回答做得又重又拖。",
            ),
            "decide": _value(
                "decide",
                short_label="decide",
                behavioral_meaning="The response should help the user judge between options with criteria and consequences.",
                target_user_effect="The user can choose more clearly without feeling overruled.",
                positive_instructions=("Make standards, tradeoffs, and likely consequences explicit.",),
                negative_instructions=("Do not overprescribe or fake certainty.",),
                response_shape_guidance=("Criteria, tradeoffs, bounded recommendation.",),
                grounding_tool_implications=("Use user values and constraints first.",),
                model_summary_en="Decide mode: build judgment through criteria and tradeoffs rather than false certainty.",
                model_summary_zh="决策模式：通过标准与取舍来帮助判断，而不是给出假装确定的替代思考。",
            ),
            "reframe": _value(
                "reframe",
                short_label="reframe",
                behavioral_meaning="The response should change the meaning frame so the user can interpret the situation more truthfully and less destructively.",
                target_user_effect="The user feels less trapped by a damaging story and more able to act.",
                positive_instructions=("Use evidence to loosen the harmful frame.",),
                negative_instructions=("Do not endorse self-negating identity narratives.",),
                response_shape_guidance=("Evidence-based reframe plus a gentle next move.",),
                grounding_tool_implications=("Use concrete evidence and trajectory, not platitudes.",),
                model_summary_en="Reframe mode: shift the meaning of the evidence so the user is less trapped by a harmful story.",
                model_summary_zh="重框模式：用证据改变这件事的意义解释，让用户不再被有害叙事困住。",
            ),
        },
    ),
    "intervention_family": StrategyTermDefinition(
        term="intervention_family",
        family="decision_policy",
        exposure_class="model_facing",
        runtime_owner="decision_policy",
        values={
            "clarifying_probe": _value(
                "clarifying_probe",
                short_label="clarifying probe",
                behavioral_meaning="Use one targeted question to unlock the next accurate move.",
                target_user_effect="The user supplies the missing fact with minimal friction.",
                positive_instructions=("Ask the highest-value question only.",),
                negative_instructions=("Do not turn clarification into an interview.",),
                response_shape_guidance=("One question, one reason, no extra branches.",),
                grounding_tool_implications=("Missing facts outrank expansion.",),
                model_summary_en="Use one targeted clarification to unlock the next accurate move.",
                model_summary_zh="用一个针对性澄清问题解锁下一步，不要展开成盘问。",
            ),
            "understanding_repair": _value(
                "understanding_repair",
                short_label="understanding repair",
                behavioral_meaning="Repair the user's mental model.",
                target_user_effect="Conceptual clarity improves.",
                positive_instructions=("Bridge the misunderstanding and explain the hinge point.",),
                negative_instructions=("Do not give only motivational language.",),
                response_shape_guidance=("Explain the hinge point, then apply it.",),
                grounding_tool_implications=("Use examples and grounded evidence.",),
                model_summary_en="Repair the user's mental model and make the hinge point explicit.",
                model_summary_zh="修复用户的理解模型，把真正的卡点讲透。",
            ),
            "trajectory_review": _value(
                "trajectory_review",
                short_label="trajectory review",
                behavioral_meaning="Compare what was tried, what changed, and what should be adjusted.",
                target_user_effect="The user sees the path more clearly and trusts the adjustment.",
                positive_instructions=("Use recent interventions and outcomes as evidence.",),
                negative_instructions=("Do not ignore recent history.",),
                response_shape_guidance=("What changed, what stayed hard, what changes next.",),
                grounding_tool_implications=("Trajectory evidence matters.",),
                model_summary_en="Review the trajectory and adapt based on what changed.",
                model_summary_zh="基于真实轨迹复盘并调整，而不是假装每轮都从零开始。",
            ),
            "criteria_construction": _value(
                "criteria_construction",
                short_label="criteria construction",
                behavioral_meaning="Build standards for judgment before forcing a choice.",
                target_user_effect="The user can judge more clearly and with less regret.",
                positive_instructions=("Name the criteria and how each option scores.",),
                negative_instructions=("Do not jump straight to a verdict.",),
                response_shape_guidance=("Criteria first, recommendation second.",),
                grounding_tool_implications=("Use the user's constraints as scoring rules.",),
                model_summary_en="Build decision criteria before pushing a verdict.",
                model_summary_zh="先搭建判断标准，再谈倾向结论。",
            ),
            "decision_navigation": _value(
                "decision_navigation",
                short_label="decision navigation",
                behavioral_meaning="Guide the user through a choice without taking over agency.",
                target_user_effect="The user can move through the decision with structure and ownership.",
                positive_instructions=("Provide a bounded recommendation and preserve freedom.",),
                negative_instructions=("Do not overtake the user's judgment.",),
                response_shape_guidance=("Map the decision, then suggest a next checkpoint.",),
                grounding_tool_implications=("Keep reversibility visible.",),
                model_summary_en="Guide the decision with structure while preserving the user's agency.",
                model_summary_zh="用结构帮用户穿过决策，但不要替用户夺走判断权。",
            ),
            "identity_repair": _value(
                "identity_repair",
                short_label="identity repair",
                behavioral_meaning="Repair a harmful self-story.",
                target_user_effect="The user can reinterpret the evidence without self-attack.",
                positive_instructions=("Use evidence and trajectory to weaken the harmful identity claim.",),
                negative_instructions=("Do not feed shame narratives.",),
                response_shape_guidance=("Reframe meaning first, action second.",),
                grounding_tool_implications=("Evidence beats platitudes.",),
                model_summary_en="Repair the harmful self-story with evidence and trajectory.",
                model_summary_zh="用证据和轨迹修复有害自我叙事。",
            ),
            "load_shedding": _value(
                "load_shedding",
                short_label="load shedding",
                behavioral_meaning="Reduce the cognitive and behavioral load immediately.",
                target_user_effect="The user can restart without overload.",
                positive_instructions=("Cut scope, lighten difficulty, and make the move easy to start.",),
                negative_instructions=("Do not increase pressure or breadth.",),
                response_shape_guidance=("One lighter move with a fallback.",),
                grounding_tool_implications=("Session-scoped reversible adjustments first.",),
                model_summary_en="Reduce load immediately so the user can restart without overload.",
                model_summary_zh="立刻降载，让用户能在不过载的情况下重新开始。",
            ),
            "scaffolded_activation": _value(
                "scaffolded_activation",
                short_label="scaffolded activation",
                behavioral_meaning="Help the user begin through structure and scaffolding.",
                target_user_effect="The user starts the next move instead of staying stuck.",
                positive_instructions=("Give a concrete next move with enough scaffold to start.",),
                negative_instructions=("Do not turn activation into pressure theater.",),
                response_shape_guidance=("Concrete next move plus a simple fallback if it slips.",),
                grounding_tool_implications=("Scaffold more when friction is high.",),
                model_summary_en="Activate the user through structure and a concrete next move, not pressure.",
                model_summary_zh="通过结构和具体下一步来启动用户，而不是靠施压表演。",
            ),
            "diagnostic_rebalance": _value(
                "diagnostic_rebalance",
                short_label="diagnostic rebalance",
                behavioral_meaning="Keep the reply cautious while competing diagnoses are still active.",
                target_user_effect="The user gets a safe next move without premature certainty.",
                positive_instructions=("Name ambiguity and choose the safest informative move.",),
                negative_instructions=("Do not overcommit to one story too early.",),
                response_shape_guidance=("State the ambiguity, then choose the safest next move.",),
                grounding_tool_implications=("Prefer reversible moves.",),
                model_summary_en="Keep the move cautious while multiple diagnoses remain plausible.",
                model_summary_zh="在多种诊断都还合理时，用更谨慎、更可逆的方式推进。",
            ),
        },
    ),
    "reversibility_level": StrategyTermDefinition(
        term="reversibility_level",
        family="decision_policy",
        exposure_class="model_facing",
        runtime_owner="decision_policy",
        values={
            "high": _value(
                "high",
                short_label="high reversibility",
                behavioral_meaning="The move should stay lightweight, session-scoped, and easy to change.",
                target_user_effect="The user is not trapped by an overcommitted response.",
                positive_instructions=("Use low-cost, revisable moves.",),
                negative_instructions=("Do not lock the user into a heavy commitment.",),
                response_shape_guidance=("Small move, clear escape hatch.",),
                grounding_tool_implications=("Prefer session-layer adjustments.",),
                model_summary_en="Keep the move highly reversible and easy to change if the diagnosis shifts.",
                model_summary_zh="让动作保持高度可逆，若判断变化也能轻松改向。",
            ),
            "medium": _value(
                "medium",
                short_label="medium reversibility",
                behavioral_meaning="The move can be somewhat stronger, but should still be easy to revise.",
                target_user_effect="The user gets meaningful direction without overcommitment.",
                positive_instructions=("Be useful and specific, but keep revision easy.",),
                negative_instructions=("Do not harden a medium-confidence move into a fixed path.",),
                response_shape_guidance=("Specific guidance with visible adaptability.",),
                grounding_tool_implications=("Keep fallback logic visible.",),
                model_summary_en="Be reasonably specific, but keep the path easy to revise.",
                model_summary_zh="可以更具体一些，但仍要保留明显的修正空间。",
            ),
            "low": _value(
                "low",
                short_label="low reversibility",
                behavioral_meaning="The runtime has enough evidence for stronger, more stable guidance.",
                target_user_effect="The user gets a firmer direction when the evidence really supports it.",
                positive_instructions=("Give firmer guidance when the evidence base is strong.",),
                negative_instructions=("Do not use firmness as a substitute for evidence.",),
                response_shape_guidance=("Clear recommendation and rationale.",),
                grounding_tool_implications=("Episode-level implications may be acceptable.",),
                model_summary_en="The evidence can support firmer guidance here, but the rationale still needs to stay visible.",
                model_summary_zh="当前证据允许更稳一些的建议，但依据仍要清楚可见。",
            ),
        },
    ),
    "plan_mode": StrategyTermDefinition(
        term="plan_mode",
        family="planning_strategy",
        exposure_class="model_facing",
        runtime_owner="planning_strategy_compiler",
        values={
            "full": _value(
                "full",
                short_label="full plan",
                behavioral_meaning="A fuller plan is appropriate and should be explicit about structure and evidence.",
                target_user_effect="The user gets a real plan rather than a placeholder.",
                positive_instructions=("Deliver a true plan with structure, grounding, and adaptation logic.",),
                negative_instructions=("Do not downgrade into vague advice without a real blocker.",),
                response_shape_guidance=("Cover the required planning sections explicitly.",),
                grounding_tool_implications=("Grounding still applies when required.",),
                model_summary_en="A real full plan is appropriate here. Give a structured plan with explicit sections, not generic advice.",
                model_summary_zh="这里适合给真实完整计划。请给出结构化计划，而不是泛泛建议。",
            ),
            "provisional": _value(
                "provisional",
                short_label="provisional plan",
                behavioral_meaning="Planning is allowed, but it must stay narrowed and assumption-aware.",
                target_user_effect="The user gets useful direction without mistaking it for a settled plan.",
                positive_instructions=("State assumptions and keep the horizon narrow.",),
                negative_instructions=("Do not pretend the plan is fully grounded or complete.",),
                response_shape_guidance=("Assumptions, reduced horizon, next action, fallback.",),
                grounding_tool_implications=("Say what missing evidence would change the plan.",),
                model_summary_en="A provisional plan is appropriate: narrow the horizon, name assumptions, and avoid pretending it is final.",
                model_summary_zh="这里适合暂定计划：缩窄时间窗，写明假设，不要假装它已经完全定型。",
            ),
            "next_step_only": _value(
                "next_step_only",
                short_label="next step only",
                behavioral_meaning="The system should not generate a multi-step plan yet.",
                target_user_effect="The user gets one unblocker instead of an unusable plan.",
                positive_instructions=("Give one next action and one unlock question or blocker.",),
                negative_instructions=("Do not produce a multi-day or multi-phase plan.",),
                response_shape_guidance=("Goal frame, withhold reason, next action, unlock question.",),
                grounding_tool_implications=("Blockers outrank scope expansion.",),
                model_summary_en="Do not produce a real plan yet. Give one next action and one unlock question or blocker.",
                model_summary_zh="现在不要展开成真实计划。给一个下一步和一个最高价值解锁问题或阻塞点就够了。",
            ),
        },
    ),
    "plan_depth": StrategyTermDefinition(
        term="plan_depth",
        family="planning_strategy",
        exposure_class="model_facing",
        runtime_owner="planning_strategy_compiler",
        values={
            "light": _value(
                "light",
                short_label="light depth",
                behavioral_meaning="Keep the plan compact and easy to process.",
                target_user_effect="The user can start without cognitive overload.",
                positive_instructions=("Use a lighter planning payload.",),
                negative_instructions=("Do not overbuild the plan.",),
                response_shape_guidance=("Shorter sections and less branching.",),
                grounding_tool_implications=("Favor one-step realism over completeness theater.",),
                model_summary_en="Keep the planning payload light and easy to process.",
                model_summary_zh="把规划负荷做轻一点，保证用户能接得住。",
            ),
            "standard": _value(
                "standard",
                short_label="standard depth",
                behavioral_meaning="Use a balanced amount of structure and detail.",
                target_user_effect="The user gets enough detail to act without bloat.",
                positive_instructions=("Use balanced detail.",),
                negative_instructions=("Do not become either too thin or too dense.",),
                response_shape_guidance=("Balanced structure and detail.",),
                grounding_tool_implications=("Stay explicit where the contract requires it.",),
                model_summary_en="Use balanced planning detail.",
                model_summary_zh="使用适中的规划细节，不要过薄也不要过重。",
            ),
            "deep": _value(
                "deep",
                short_label="deep depth",
                behavioral_meaning="The plan should be more fully reasoned and explicit.",
                target_user_effect="The user gets a more complete path when the brief supports it.",
                positive_instructions=("Be explicit about sequencing, assumptions, and adaptation.",),
                negative_instructions=("Do not substitute density for clarity.",),
                response_shape_guidance=("More explicit structure, still readable.",),
                grounding_tool_implications=("Make evidence and constraints visible.",),
                model_summary_en="Use deeper planning detail, but keep the structure readable.",
                model_summary_zh="这里可以更深入规划，但结构仍要清晰可读。",
            ),
        },
    ),
    "pacing_profile": StrategyTermDefinition(
        term="pacing_profile",
        family="planning_strategy",
        exposure_class="model_facing",
        runtime_owner="planning_strategy_compiler",
        values={
            "light": _value(
                "light",
                short_label="light pacing",
                behavioral_meaning="Reduce load and protect restartability.",
                target_user_effect="The user can begin without feeling crushed by the plan.",
                positive_instructions=("Keep the pace forgiving and low-pressure.",),
                negative_instructions=("Do not push intensity.",),
                response_shape_guidance=("Smaller steps and easier fallback.",),
                grounding_tool_implications=("Capacity limits are primary constraints.",),
                model_summary_en="Keep the pacing light and forgiving.",
                model_summary_zh="节奏要轻、宽、低压力，先保护可启动性。",
            ),
            "steady": _value(
                "steady",
                short_label="steady pacing",
                behavioral_meaning="Use a sustainable, even pace.",
                target_user_effect="The user gets momentum that can hold across days.",
                positive_instructions=("Prefer a sustainable cadence.",),
                negative_instructions=("Do not introduce unnecessary urgency.",),
                response_shape_guidance=("Evenly paced sequence and checkpoints.",),
                grounding_tool_implications=("Sustainability matters.",),
                model_summary_en="Use a sustainable steady pace.",
                model_summary_zh="采用可持续、均衡的节奏。",
            ),
            "push": _value(
                "push",
                short_label="push pacing",
                behavioral_meaning="There is legitimate time pressure, but the plan must still stay realistic.",
                target_user_effect="The user sees urgency without being set up to fail.",
                positive_instructions=("Acknowledge urgency and tighten focus realistically.",),
                negative_instructions=("Do not confuse urgency with fantasy intensity.",),
                response_shape_guidance=("Tighter sequence, but still realistic.",),
                grounding_tool_implications=("Use deadlines without overpromising.",),
                model_summary_en="There is real urgency, but keep the plan realistic rather than fantasized.",
                model_summary_zh="这里确实有紧迫性，但节奏再紧也要现实，不能变成幻想式冲刺。",
            ),
        },
    ),
    "grounding_mode": StrategyTermDefinition(
        term="grounding_mode",
        family="planning_strategy",
        exposure_class="model_facing",
        runtime_owner="planning_strategy_compiler",
        values={
            "mandatory": _value(
                "mandatory",
                short_label="mandatory grounding",
                behavioral_meaning="User materials or evidence must appear explicitly in the output.",
                target_user_effect="The user can trust that the plan actually reflects their materials.",
                positive_instructions=("Explicitly cite or name the user materials used.",),
                negative_instructions=("Do not replace missing grounding with generic claims.",),
                response_shape_guidance=("Include a visible grounding basis section.",),
                grounding_tool_implications=("Use attached material names when available.",),
                model_summary_en="Grounding is mandatory: the answer must explicitly use the user's materials or evidence, not generic substitution.",
                model_summary_zh="这里必须落到用户材料或证据：回答里要显式用到它们，不能用泛泛知识替代。",
            ),
            "required_from_profile": _value(
                "required_from_profile",
                short_label="profile-required grounding",
                behavioral_meaning="The response must at least stay anchored in known user profile truths and constraints.",
                target_user_effect="The plan reflects the user's known context.",
                positive_instructions=("Anchor in the user's known constraints and profile truths.",),
                negative_instructions=("Do not answer as if the user were generic.",),
                response_shape_guidance=("Make user-specific constraints visible.",),
                grounding_tool_implications=("Profile evidence counts as grounding here.",),
                model_summary_en="Grounding is required from the user's known profile and constraints.",
                model_summary_zh="这里至少要扎根在用户已知画像与约束上，不能把用户当成通用人设来答。",
            ),
            "preferred": _value(
                "preferred",
                short_label="preferred grounding",
                behavioral_meaning="Grounding should lead when available, but light general knowledge can supplement.",
                target_user_effect="The response stays specific when possible without stalling unnecessarily.",
                positive_instructions=("Use grounding first when available.",),
                negative_instructions=("Do not ignore user-specific evidence.",),
                response_shape_guidance=("Prefer grounded phrasing, then supplement if needed.",),
                grounding_tool_implications=("Evidence first, general knowledge second.",),
                model_summary_en="Grounding is preferred: use user-specific evidence first when it exists.",
                model_summary_zh="这里优先用用户特定证据；有就先用，没有再谨慎补一般知识。",
            ),
            "light": _value(
                "light",
                short_label="light grounding",
                behavioral_meaning="The response can rely more on general guidance because hard grounding is not essential here.",
                target_user_effect="The user still gets a useful move without unnecessary ceremony.",
                positive_instructions=("Stay useful even when heavy grounding is unnecessary.",),
                negative_instructions=("Do not invent fake citations.",),
                response_shape_guidance=("Light grounding, compact move.",),
                grounding_tool_implications=("General guidance is acceptable within limits.",),
                model_summary_en="Heavy grounding is not essential here, so keep the move useful and compact without inventing evidence.",
                model_summary_zh="这里不需要重型证据链，可以更轻地回答，但不要伪造依据。",
            ),
        },
    ),
    "fallback_policy": StrategyTermDefinition(
        term="fallback_policy",
        family="planning_strategy",
        exposure_class="model_facing",
        runtime_owner="planning_strategy_compiler",
        values={
            "ask_more": _value(
                "ask_more",
                short_label="ask more",
                behavioral_meaning="If the plan would be weak, stop and ask for the blocker-clearing fact.",
                target_user_effect="The user is not given a fake plan.",
                positive_instructions=("Prefer one clarification over a brittle plan.",),
                negative_instructions=("Do not bluff completeness.",),
                response_shape_guidance=("Withhold broad planning and ask the blocker question.",),
                grounding_tool_implications=("Information gaps outrank completion pressure.",),
                model_summary_en="If the plan would be weak, ask for the missing fact instead of bluffing.",
                model_summary_zh="如果计划会很虚，就先问缺失信息，不要硬凑完整度。",
            ),
            "downgrade_to_provisional": _value(
                "downgrade_to_provisional",
                short_label="downgrade to provisional",
                behavioral_meaning="When full certainty is not justified, narrow the scope and make assumptions explicit.",
                target_user_effect="The user still gets useful structure, but honestly bounded.",
                positive_instructions=("Shrink the plan and name assumptions.",),
                negative_instructions=("Do not keep pretending the plan is fully grounded.",),
                response_shape_guidance=("Provisional structure with explicit uncertainty.",),
                grounding_tool_implications=("Visible uncertainty is required.",),
                model_summary_en="If the full version is too weak, downgrade to a narrower provisional plan with explicit assumptions.",
                model_summary_zh="如果完整计划站不住，就降级成更窄的暂定计划，并把假设说清楚。",
            ),
            "shrink_scope_then_retry": _value(
                "shrink_scope_then_retry",
                short_label="shrink scope",
                behavioral_meaning="Reduce the plan payload before trying again.",
                target_user_effect="The user gets something usable instead of overload.",
                positive_instructions=("Cut breadth before increasing pressure.",),
                negative_instructions=("Do not keep all the original scope when the plan is too heavy.",),
                response_shape_guidance=("Smaller plan, then next move.",),
                grounding_tool_implications=("Capacity is a hard constraint.",),
                model_summary_en="If the current plan is too heavy, shrink scope before trying again.",
                model_summary_zh="如果当前计划太重，就先缩范围，再继续。",
            ),
            "use_materials_or_downgrade": _value(
                "use_materials_or_downgrade",
                short_label="use materials or downgrade",
                behavioral_meaning="The response must either ground in user materials or explicitly reduce the planning claim.",
                target_user_effect="The user gets either grounded specificity or an honest downgrade.",
                positive_instructions=("Use materials by name, or openly reduce scope and certainty.",),
                negative_instructions=("Do not claim grounded planning without grounded materials.",),
                response_shape_guidance=("Ground explicitly, or downgrade explicitly.",),
                grounding_tool_implications=("Mandatory grounding is binding.",),
                model_summary_en="Either use the user's materials explicitly or openly downgrade the planning claim.",
                model_summary_zh="要么明确用到用户材料，要么明确降低计划的范围与确定性。",
            ),
            "revise": _value(
                "revise",
                short_label="revise",
                behavioral_meaning="The answer should correct weaknesses before approval rather than bluff through them.",
                target_user_effect="The user gets a cleaner, safer plan.",
                positive_instructions=("Revise weak sections rather than forcing approval.",),
                negative_instructions=("Do not accept visible weaknesses as-is.",),
                response_shape_guidance=("Repair the missing sections and constraints.",),
                grounding_tool_implications=("Revision should respect the contract.",),
                model_summary_en="Revise the weak plan instead of bluffing through the weaknesses.",
                model_summary_zh="计划有明显短板时先修，再给，不要硬撑过去。",
            ),
        },
    ),
    "session_mode": StrategyTermDefinition(
        term="session_mode",
        family="strategy_state",
        exposure_class="mixed",
        runtime_owner="user_strategy_state",
        values={
            "recovery": _value(
                "recovery",
                short_label="recovery session",
                behavioral_meaning="Protect restartability and reduce burden.",
                target_user_effect="The user can re-enter the task without overload.",
                positive_instructions=("Favor recovery-compatible moves.",),
                negative_instructions=("Do not intensify demands.",),
                response_shape_guidance=("Lower burden and narrower scope.",),
                grounding_tool_implications=("Respect capacity limits.",),
                model_summary_en="The session is in recovery mode, so protect restartability and reduce burden.",
                model_summary_zh="当前会话偏恢复模式，所以优先保护可重启性并降低负担。",
            ),
            "guided": _value(
                "guided",
                short_label="guided session",
                behavioral_meaning="The user benefits from crisp structure and concrete next moves.",
                target_user_effect="The user can move with support and structure.",
                positive_instructions=("Provide structure and a clear next action.",),
                negative_instructions=("Do not leave the move too abstract.",),
                response_shape_guidance=("Guided structure and crisp next action.",),
                grounding_tool_implications=("Scaffolding matters.",),
                model_summary_en="The session is guided, so structure and concrete next moves matter.",
                model_summary_zh="当前会话偏引导模式，所以结构和具体下一步很重要。",
            ),
            "exploratory": _value(
                "exploratory",
                short_label="exploratory session",
                behavioral_meaning="The turn should preserve comparison and reflection rather than force closure.",
                target_user_effect="The user can explore the space without feeling cornered.",
                positive_instructions=("Allow comparison and reflection.",),
                negative_instructions=("Do not force premature closure.",),
                response_shape_guidance=("Structured exploration before commitment.",),
                grounding_tool_implications=("Comparison is part of the task.",),
                model_summary_en="The session is exploratory, so preserve comparison and reflection instead of forcing closure.",
                model_summary_zh="当前会话偏探索模式，所以保留比较与思考空间，不要过早封口。",
            ),
            "review": _value(
                "review",
                short_label="review session",
                behavioral_meaning="The user needs consolidation, correction, and reflective checking more than expansion.",
                target_user_effect="The user leaves with a cleaner and more stable understanding.",
                positive_instructions=("Prioritize correction, consolidation, and review.",),
                negative_instructions=("Do not expand scope into too much new content.",),
                response_shape_guidance=("Review framing, correction, and reinforcement.",),
                grounding_tool_implications=("Use existing evidence and prior work to correct understanding.",),
                model_summary_en="The session is in review mode, so prioritize consolidation and correction over expanding into new material.",
                model_summary_zh="当前会话偏复盘模式，所以优先纠错、巩固和回看，不要急着扩展新内容。",
            ),
        },
    ),
    "explanation_style": StrategyTermDefinition(
        term="explanation_style",
        family="strategy_state",
        exposure_class="mixed",
        runtime_owner="user_strategy_state",
        values={
            "conceptual": _value(
                "conceptual",
                short_label="conceptual explanation",
                behavioral_meaning="The response should foreground the underlying idea before procedural detail.",
                target_user_effect="The user gets a clearer conceptual frame before acting.",
                positive_instructions=("Lead with the idea and the principle behind it.",),
                negative_instructions=("Do not drown the user in procedural steps too early.",),
                response_shape_guidance=("Concept first, then concrete application.",),
                grounding_tool_implications=("Use examples only to support the concept.",),
                model_summary_en="Use a concept-first explanation style so the user understands the idea before the procedure.",
                model_summary_zh="当前更适合概念优先的解释方式，先把原理讲清，再落到做法。",
            ),
            "example_based": _value(
                "example_based",
                short_label="example-based explanation",
                behavioral_meaning="The response should anchor abstract points in concrete examples.",
                target_user_effect="The user can understand the idea through a concrete case first.",
                positive_instructions=("Use a concrete example before abstracting upward.",),
                negative_instructions=("Do not stay purely abstract if an example would unlock understanding.",),
                response_shape_guidance=("Example first, then abstraction.",),
                grounding_tool_implications=("Prefer examples grounded in the user's materials when possible.",),
                model_summary_en="Use an example-led explanation so the user can grasp the point through a concrete case first.",
                model_summary_zh="当前更适合例子优先的解释方式，先用具体例子搭桥，再抽象总结。",
            ),
            "step_by_step": _value(
                "step_by_step",
                short_label="step-by-step explanation",
                behavioral_meaning="The response should unfold in clear ordered steps with minimal jumps.",
                target_user_effect="The user can follow the reasoning without getting lost between steps.",
                positive_instructions=("Break the explanation into explicit ordered steps.",),
                negative_instructions=("Do not skip links in the chain of reasoning.",),
                response_shape_guidance=("Ordered steps with clear transitions.",),
                grounding_tool_implications=("Procedural clarity matters more than compression.",),
                model_summary_en="Use a step-by-step explanation style so the reasoning unfolds in clear ordered steps.",
                model_summary_zh="当前更适合按步骤解释，把推理链条拆开，不要跳步。",
            ),
        },
    ),
    "retrieval_emphasis": StrategyTermDefinition(
        term="retrieval_emphasis",
        family="strategy_state",
        exposure_class="mixed",
        runtime_owner="user_strategy_state",
        values={
            "user_materials": _value(
                "user_materials",
                short_label="user-materials first",
                behavioral_meaning="Evidence and examples should come from the user's own materials whenever possible.",
                target_user_effect="The user gets a response grounded in their own learning context.",
                positive_instructions=("Prefer the user's materials and current plan as the grounding base.",),
                negative_instructions=("Do not substitute generic knowledge for available user evidence.",),
                response_shape_guidance=("Ground claims in user-owned materials first.",),
                grounding_tool_implications=("Retrieval should favor user-provided artifacts.",),
                model_summary_en="Ground the response in the user's own materials first, and use general knowledge only as support.",
                model_summary_zh="当前应优先依赖用户自己的材料和当前计划来校准内容，通用知识只作补充。",
            ),
            "balanced": _value(
                "balanced",
                short_label="balanced retrieval",
                behavioral_meaning="Use user materials when they help, but do not force them into every sentence.",
                target_user_effect="The user gets a grounded but not over-constrained answer.",
                positive_instructions=("Balance user materials with general explanation when needed.",),
                negative_instructions=("Do not overfit the answer to weak or irrelevant material.",),
                response_shape_guidance=("Grounded where useful, flexible where needed.",),
                grounding_tool_implications=("Blend user evidence with general explanation judiciously.",),
                model_summary_en="Use a balanced grounding posture: prefer the user's context when it helps, but stay flexible when it does not.",
                model_summary_zh="当前采用平衡型校准：用户材料有帮助时优先使用，但不要生硬套用到每一句话里。",
            ),
            "general_knowledge": _value(
                "general_knowledge",
                short_label="general-knowledge support",
                behavioral_meaning="The response can lean more on general knowledge when user materials are sparse or not decisive.",
                target_user_effect="The user still gets a complete answer when personal materials are missing.",
                positive_instructions=("Use general knowledge to fill gaps when user materials are insufficient.",),
                negative_instructions=("Do not pretend user-specific grounding exists when it does not.",),
                response_shape_guidance=("Complete the answer with careful general knowledge.",),
                grounding_tool_implications=("Generic grounding is acceptable when evidence is sparse.",),
                model_summary_en="User materials are not enough here, so it is acceptable to rely more on careful general knowledge.",
                model_summary_zh="当前用户材料不足以支撑全部内容，所以可以更主动地用通用知识补齐，但不要假装有用户专属证据。",
            ),
        },
    ),
    "intervention_intensity": StrategyTermDefinition(
        term="intervention_intensity",
        family="strategy_state",
        exposure_class="mixed",
        runtime_owner="user_strategy_state",
        values={
            "low": _value(
                "low",
                short_label="light intervention",
                behavioral_meaning="The response should stay light, minimal, and non-overloading.",
                target_user_effect="The user gets support without feeling crowded or pressured.",
                positive_instructions=("Keep the move light and avoid stacking too many demands.",),
                negative_instructions=("Do not flood the turn with multiple heavy actions.",),
                response_shape_guidance=("Lightweight, low-load response shape.",),
                grounding_tool_implications=("Favor minimum viable support.",),
                model_summary_en="Keep the intervention light so the response does not overload the user.",
                model_summary_zh="当前干预强度应保持轻量，避免一下子塞入过多动作或约束。",
            ),
            "medium": _value(
                "medium",
                short_label="steady intervention",
                behavioral_meaning="The response can guide and structure the turn without becoming forceful.",
                target_user_effect="The user gets steady guidance without excessive pressure.",
                positive_instructions=("Provide steady guidance and structure.",),
                negative_instructions=("Do not become either too passive or too forceful.",),
                response_shape_guidance=("Steady guidance with one clear move.",),
                grounding_tool_implications=("Moderate structure is appropriate.",),
                model_summary_en="Use a steady intervention level: structured and supportive, but not forceful.",
                model_summary_zh="当前干预强度以稳定为主：给出结构和引导，但不要变成高压推进。",
            ),
            "high": _value(
                "high",
                short_label="directive intervention",
                behavioral_meaning="The response may take a firmer stance and give tighter action guidance when warranted.",
                target_user_effect="The user gets more decisive structure when ambiguity or drift is too costly.",
                positive_instructions=("Be more explicit about the recommended move and constraints.",),
                negative_instructions=("Do not use firmness as an excuse for pressure or loss of reversibility.",),
                response_shape_guidance=("Clearer judgment and firmer guidance.",),
                grounding_tool_implications=("Tighter structure is acceptable when still justified.",),
                model_summary_en="A firmer intervention is acceptable here, but it still needs to stay justified and reversible.",
                model_summary_zh="当前可以更明确地下判断和给行动约束，但仍要保持有根据、可回退。",
            ),
        },
    ),
    "support_posture": StrategyTermDefinition(
        term="support_posture",
        family="strategy_state",
        exposure_class="mixed",
        runtime_owner="user_strategy_state.push_vs_support",
        values={
            "support_first": _value(
                "support_first",
                short_label="support-first posture",
                behavioral_meaning="The response should lead with support, acknowledgement, and a gentle handoff into action.",
                target_user_effect="The user feels carried before being pushed.",
                positive_instructions=("Support and acknowledge first, then introduce the next move gently.",),
                negative_instructions=("Do not open by pushing or tightening too fast.",),
                response_shape_guidance=("Support first, then light action handoff.",),
                grounding_tool_implications=("Emotional pacing matters.",),
                model_summary_en="Use a support-first posture: lead with support and only then introduce a gentle next move.",
                model_summary_zh="当前更适合支持优先：先承接和支持，再轻轻把用户带到下一步。",
            ),
            "balanced": _value(
                "balanced",
                short_label="balanced posture",
                behavioral_meaning="The response should balance support with forward motion.",
                target_user_effect="The user feels both understood and guided.",
                positive_instructions=("Balance support with clear movement.",),
                negative_instructions=("Do not get stuck in pure reassurance or pure pressure.",),
                response_shape_guidance=("Balanced support and forward motion.",),
                grounding_tool_implications=("Balance acknowledgment with structure.",),
                model_summary_en="Use a balanced posture: combine support with a clear forward move.",
                model_summary_zh="当前更适合平衡型姿态：既要承接，也要给出清晰推进。",
            ),
            "directive": _value(
                "directive",
                short_label="directive posture",
                behavioral_meaning="The response can be more direct and convergent about what to do next.",
                target_user_effect="The user gets firmer convergence and less ambiguity.",
                positive_instructions=("Be more direct about the next move and convergence path.",),
                negative_instructions=("Do not confuse directness with harshness.",),
                response_shape_guidance=("More convergent and direct response shape.",),
                grounding_tool_implications=("Direct structure is acceptable when still reversible.",),
                model_summary_en="Use a more directive posture: converge more directly on the next move without becoming harsh.",
                model_summary_zh="当前可以更直接地收束到下一步，但不要把直接变成生硬或高压。",
            ),
        },
    ),
}


INVENTORY_ENTRIES: tuple[dict[str, str], ...] = (
    {
        "term_family": "decision_policy",
        "term": "experience_mode",
        "value": "clarify|explain|review|stabilize|mobilize|decide|reframe",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_decision_policy_section",
        "risk_level": "high",
    },
    {
        "term_family": "decision_policy",
        "term": "intervention_family",
        "value": "clarifying_probe|understanding_repair|trajectory_review|criteria_construction|decision_navigation|identity_repair|load_shedding|scaffolded_activation|diagnostic_rebalance",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_decision_policy_section",
        "risk_level": "high",
    },
    {
        "term_family": "decision_policy",
        "term": "reversibility_level",
        "value": "high|medium|low",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_decision_policy_section",
        "risk_level": "high",
    },
    {
        "term_family": "decision",
        "term": "primary_residual",
        "value": "R_e|R_n|R_c|R_i|R_mixed|R_unknown",
        "source_surface": "situation_brief_prompt",
        "exposure_class": "mixed",
        "current_rendering_path": "situation_brief.format_situation_brief_section",
        "risk_level": "medium",
    },
    {
        "term_family": "decision",
        "term": "loop_type",
        "value": "truth_seeking|normative|identity_repair",
        "source_surface": "situation_brief_prompt",
        "exposure_class": "mixed",
        "current_rendering_path": "situation_brief.format_situation_brief_section",
        "risk_level": "high",
    },
    {
        "term_family": "decision",
        "term": "confidence_label",
        "value": "high|medium|low",
        "source_surface": "situation_brief_prompt",
        "exposure_class": "mixed",
        "current_rendering_path": "situation_brief.format_situation_brief_section",
        "risk_level": "medium",
    },
    {
        "term_family": "planning",
        "term": "planning_readiness",
        "value": "low|medium|high",
        "source_surface": "prompt_responder",
        "exposure_class": "mixed",
        "current_rendering_path": "prompts._format_decision_policy_section",
        "risk_level": "medium",
    },
    {
        "term_family": "planning",
        "term": "planning_readiness_action",
        "value": "ask|provisional|proceed",
        "source_surface": "prompt_responder",
        "exposure_class": "mixed",
        "current_rendering_path": "prompts._format_decision_policy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "plan_mode",
        "value": "full|provisional|next_step_only",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_planning_strategy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "plan_depth",
        "value": "light|standard|deep",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_planning_strategy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "pacing_profile",
        "value": "light|steady|push",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_planning_strategy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "grounding_mode",
        "value": "mandatory|required_from_profile|preferred|light",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_planning_strategy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "fallback_policy",
        "value": "ask_more|downgrade_to_provisional|shrink_scope_then_retry|use_materials_or_downgrade|revise",
        "source_surface": "prompt_responder",
        "exposure_class": "model_facing",
        "current_rendering_path": "prompts._format_planning_strategy_section",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "plan_mode",
        "value": "full|provisional|next_step_only",
        "source_surface": "planner_constraints",
        "exposure_class": "model_facing",
        "current_rendering_path": "lang_graph_planner._build_constraints_context",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "plan_depth",
        "value": "light|standard|deep",
        "source_surface": "planner_constraints",
        "exposure_class": "model_facing",
        "current_rendering_path": "lang_graph_planner._build_constraints_context",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "grounding_mode",
        "value": "mandatory|required_from_profile|preferred|light",
        "source_surface": "planner_constraints",
        "exposure_class": "model_facing",
        "current_rendering_path": "lang_graph_planner._build_constraints_context",
        "risk_level": "high",
    },
    {
        "term_family": "planning_strategy",
        "term": "fallback_policy",
        "value": "ask_more|downgrade_to_provisional|shrink_scope_then_retry|use_materials_or_downgrade|revise",
        "source_surface": "planner_constraints",
        "exposure_class": "model_facing",
        "current_rendering_path": "lang_graph_planner._build_constraints_context",
        "risk_level": "high",
    },
    {
        "term_family": "strategy_state",
        "term": "session_mode",
        "value": "recovery|guided|exploratory|review",
        "source_surface": "semantic_control",
        "exposure_class": "mixed",
        "current_rendering_path": "ai_strategy_renderer selected strategy-state rendering",
        "risk_level": "medium",
    },
    {
        "term_family": "strategy_state",
        "term": "explanation_style",
        "value": "conceptual|example_based|step_by_step",
        "source_surface": "semantic_control",
        "exposure_class": "mixed",
        "current_rendering_path": "ai_strategy_renderer strategy doctrine rendering",
        "risk_level": "medium",
    },
    {
        "term_family": "strategy_state",
        "term": "retrieval_emphasis",
        "value": "user_materials|balanced|general_knowledge",
        "source_surface": "semantic_control",
        "exposure_class": "mixed",
        "current_rendering_path": "ai_strategy_renderer strategy doctrine rendering",
        "risk_level": "high",
    },
    {
        "term_family": "strategy_state",
        "term": "intervention_intensity",
        "value": "low|medium|high",
        "source_surface": "semantic_control",
        "exposure_class": "mixed",
        "current_rendering_path": "ai_strategy_renderer strategy doctrine rendering",
        "risk_level": "medium",
    },
    {
        "term_family": "strategy_state",
        "term": "support_posture",
        "value": "support_first|balanced|directive",
        "source_surface": "semantic_control",
        "exposure_class": "mixed",
        "current_rendering_path": "ai_strategy_renderer derived strategy doctrine rendering",
        "risk_level": "medium",
    },
    {
        "term_family": "body_awareness",
        "term": "primary_subsystem",
        "value": "registry-driven label",
        "source_surface": "prompt_responder",
        "exposure_class": "mixed",
        "current_rendering_path": "decision policy and situation brief body awareness rendering",
        "risk_level": "medium",
    },
)


def get_term_definition(term: str) -> StrategyTermDefinition | None:
    return TERM_DEFINITIONS.get(str(term or "").strip())


def get_value_doctrine(term: str, value: Any) -> StrategyValueDoctrine | None:
    definition = get_term_definition(term)
    if definition is None:
        return None
    return definition.get(value)


def governed_terms() -> tuple[str, ...]:
    return tuple(TERM_DEFINITIONS.keys())


def model_facing_terms() -> tuple[str, ...]:
    return tuple(
        term
        for term, definition in TERM_DEFINITIONS.items()
        if definition.exposure_class in {"model_facing", "mixed"} and not definition.internal_only
    )


def build_inventory_fixture() -> list[dict[str, str]]:
    return [dict(item) for item in INVENTORY_ENTRIES]
