# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkle/rag/v1/evidence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sparkle/rag/v1/evidence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsparkle/rag/v1/evidence.proto\x12\x0esparkle.rag.v1\"\xea\x01\n\x0c\x45videnceNode\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0f\n\x07snippet\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x12\n\nsource_uri\x18\x05 \x01(\t\x12<\n\x08metadata\x18\x06 \x03(\x0b\x32*.sparkle.rag.v1.EvidenceNode.MetadataEntry\x12\x13\n\x0bsource_type\x18\x07 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd0\x01\n\x0c\x45videncePack\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12+\n\x05nodes\x18\x03 \x03(\x0b\x32\x1c.sparkle.rag.v1.EvidenceNode\x12<\n\x08metadata\x18\x04 \x03(\x0b\x32*.sparkle.rag.v1.EvidencePack.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x35Z3github.com/sparkle/gateway/gen/sparkle/rag/v1;ragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sparkle.rag.v1.evidence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/sparkle/gateway/gen/sparkle/rag/v1;ragv1'
  _globals['_EVIDENCENODE_METADATAENTRY']._loaded_options = None
  _globals['_EVIDENCENODE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVIDENCEPACK_METADATAENTRY']._loaded_options = None
  _globals['_EVIDENCEPACK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVIDENCENODE']._serialized_start=50
  _globals['_EVIDENCENODE']._serialized_end=284
  _globals['_EVIDENCENODE_METADATAENTRY']._serialized_start=237
  _globals['_EVIDENCENODE_METADATAENTRY']._serialized_end=284
  _globals['_EVIDENCEPACK']._serialized_start=287
  _globals['_EVIDENCEPACK']._serialized_end=495
  _globals['_EVIDENCEPACK_METADATAENTRY']._serialized_start=237
  _globals['_EVIDENCEPACK_METADATAENTRY']._serialized_end=284
# @@protoc_insertion_point(module_scope)
