#!/usr/bin/env python3
"""UX component-convention ratchet guard — block NEW component/decoration debt.

Companion to `check_ui_design_tokens_ratchet.py` (which already ratchets
hardcoded colors / fontSize literals repo-wide). This guard enforces the
mobile/lib/core/design/README.md CONVENTION on the V3 canonical surfaces
(9 surfaces of U-01 + sprint surface as the 10th governance surface, A-SPEC
V1.1 N1 / 改造#7):

- raw Material buttons (ElevatedButton/FilledButton/OutlinedButton/TextButton)
- raw progress spinners (CircularProgressIndicator/LinearProgressIndicator)
- raw Chip family (RawChip/Chip/FilterChip/ChoiceChip/InputChip/ActionChip)
- private parallel component classes
  (`class _?…Chip|Pill|Badge|Capsule|Empty…|Error…|Loading… extends …`)
- hardcoded `Color(0x…)` literals in surface presentation code

Per-file counts are pinned against a frozen baseline
(`ux_component_convention_baseline.json`, generated by U-01 at fdf8204a):

- a file exceeding its baseline count, or a NEW file with any violation, fails;
- counts may only go down (ratchet). After a consolidation batch lowers
  counts, run with `--update-baseline` and commit the JSON diff.

Scanned roots (V3 reachable surfaces only — see v3-output/U-01/INVENTORY.md §1;
10th root per A-SPEC V1.1 N1):
  onboarding/home/chat/goal/task/memory/galaxy/plan presentation dirs,
  profile + persona-onboarding + unified-settings user screens,
  settings presentation dir.

Exit 0 on pass, 1 on violations.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MOBILE_LIB = REPO_ROOT / "mobile" / "lib"
BASELINE_PATH = Path(__file__).resolve().parent / "ux_component_convention_baseline.json"

SCAN_ROOTS: list[str] = [
    "features/onboarding/presentation",
    "features/home/presentation",
    "features/chat/presentation",
    "features/goal/presentation",
    "features/task/presentation",
    "features/memory/presentation",
    "features/galaxy/presentation",
    # 第 10 治理面（A-SPEC V1.1 N1 / 改造#7）：冲刺仪表盘——期末一周
    # 北极星主场景，含 sprint_screen 及同目录全部 plan 呈现代码。
    "features/plan/presentation",
    "features/settings/presentation",
    "features/user/presentation/screens/profile_screen.dart",
    "features/user/presentation/screens/persona_onboarding_screen.dart",
    "features/user/presentation/screens/unified_settings_screen.dart",
]

PATTERNS: dict[str, re.Pattern[str]] = {
    "rawButton": re.compile(r"\b(?:ElevatedButton|FilledButton|OutlinedButton|TextButton)\("),
    "rawSpinner": re.compile(r"\b(?:CircularProgressIndicator|LinearProgressIndicator)\("),
    "rawChip": re.compile(r"\b(?:RawChip|Chip|FilterChip|ChoiceChip|InputChip|ActionChip)\("),
    "parallelClass": re.compile(
        r"class\s+_?\w*?(?:Chip|Pill|Badge|Capsule|Empty\w*|Error\w*|Loading\w*)\w*\s+extends\s+\w+"
    ),
    "colorLiteral": re.compile(r"Color\(0x"),
}

# E1 (galaxy visual-hammer local palette): galaxy painter/config files keep a
# frozen colorLiteral budget but are excluded from future raises via baseline;
# they are NOT exempted from structural patterns.
E1_PAINTERS = (
    "features/galaxy/presentation/widgets/galaxy/star_map_painter.dart",
    "features/galaxy/presentation/widgets/galaxy/sector_config.dart",
)

_COMMENT_RE = re.compile(r"^\s*(?://|/\*|\*|///)")


def _code_lines(text: str) -> list[str]:
    return [ln for ln in text.splitlines() if not _COMMENT_RE.match(ln)]


def count_file_lines_text(text: str) -> dict[str, int]:
    """Pattern counts for one file's source text (comment lines skipped)."""
    lines = _code_lines(text)
    counts: dict[str, int] = {}
    for name, pat in PATTERNS.items():
        counts[name] = sum(len(pat.findall(ln)) for ln in lines)
    return counts


def count_file(path: Path) -> dict[str, int]:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {k: 0 for k in PATTERNS}
    return count_file_lines_text(text)


def scan_roots() -> list[Path]:
    files: list[Path] = []
    for rel in SCAN_ROOTS:
        p = MOBILE_LIB / rel
        if p.is_file():
            files.append(p)
        elif p.is_dir():
            files.extend(sorted(f for f in p.rglob("*.dart") if not f.name.endswith(".g.dart")))
    return files


def scan_all() -> dict[str, dict[str, int]]:
    counts: dict[str, dict[str, int]] = {}
    for f in scan_roots():
        c = count_file(f)
        if any(c.values()):
            counts["mobile/lib/" + f.relative_to(MOBILE_LIB).as_posix()] = c
    return counts


def totals(counts: dict[str, dict[str, int]]) -> dict[str, int]:
    return {name: sum(c.get(name, 0) for c in counts.values()) for name in PATTERNS}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="rewrite baseline JSON from current counts (only after a batch LOWERED counts)",
    )
    args = parser.parse_args()

    current = scan_all()
    current_totals = totals(current)

    if args.update_baseline:
        old_totals = None
        if BASELINE_PATH.exists():
            old = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
            old_totals = totals(old.get("files", {}))
        payload = {
            "comment": (
                "Frozen ratchet baseline for check_ux_component_convention.py "
                "(U-01 CONVENTION, mobile/lib/core/design/README.md). Only lower via "
                "--update-baseline after a consolidation batch; never raise."
            ),
            "files": current,
        }
        BASELINE_PATH.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        arrow = f"{old_totals} -> " if old_totals else ""
        print(f"[ux-component-convention] baseline updated: {arrow}{current_totals} ({len(current)} files)")
        return 0

    if not BASELINE_PATH.exists():
        print(f"[ux-component-convention] FAIL — baseline missing: {BASELINE_PATH}")
        return 1
    baseline = json.loads(BASELINE_PATH.read_text(encoding="utf-8")).get("files", {})
    baseline_totals = totals(baseline)

    violations: list[str] = []
    for rel, c in sorted(current.items()):
        b = baseline.get(rel)
        if b is None:
            summary = ", ".join(f"{k}={v}" for k, v in c.items() if v)
            violations.append(f"NEW FILE {rel}: {summary} (baseline: none — new UI must use core/design owners)")
            continue
        for name, pat in PATTERNS.items():
            now, base = c.get(name, 0), b.get(name, 0)
            if now > base:
                tag = " (E1 visual-hammer painter: consolidate into theme entry, do not grow)" if (
                    name == "colorLiteral" and rel.replace("mobile/lib/", "") in E1_PAINTERS
                ) else ""
                violations.append(f"{rel}: {name} {now} > baseline {base} (+{now - base}){tag}")

    if violations:
        print(
            f"[ux-component-convention] FAIL — {len(violations)} ratchet violation(s); "
            "component/decoration debt may only decrease (CONVENTION: mobile/lib/core/design/README.md)"
        )
        for v in violations:
            print(f"  {v}")
        print(
            "\nAction: use core/design owners (SparkleButton/SparkleCard/SemanticPill/TaskPill/"
            "EmptyState/CustomErrorWidget/LoadingIndicator/SparkleSkeleton/AiStatusCapsule). "
            "If a consolidation batch legitimately LOWERED counts, refresh baseline via:"
        )
        print("  python3 scripts/guards/check_ux_component_convention.py --update-baseline")
        return 1

    print(
        f"[ux-component-convention] PASS — ratchet holds: "
        + ", ".join(f"{k}={current_totals[k]}/{baseline_totals[k]}" for k in PATTERNS)
        + f" ({len(current)} files with debt)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
