// Mocks generated by Mockito 5.4.4 from annotations
// in sparkle/test/features/chat/presentation/providers/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sparkle/features/chat/data/models/chat_message_model.dart'
    as _i7;
import 'package:sparkle/features/chat/data/models/chat_response_model.dart'
    as _i2;
import 'package:sparkle/features/chat/data/models/chat_stream_events.dart'
    as _i8;
import 'package:sparkle/features/chat/data/models/expert_catalog_model.dart'
    as _i3;
import 'package:sparkle/features/chat/data/repositories/chat_repository.dart'
    as _i4;
import 'package:sparkle/features/chat/data/services/websocket_chat_service_v2.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatResponseModel_0 extends _i1.SmartFake
    implements _i2.ChatResponseModel {
  _FakeChatResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiAgentCatalog_1 extends _i1.SmartFake
    implements _i3.MultiAgentCatalog {
  _FakeMultiAgentCatalog_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertCatalogExpert_2 extends _i1.SmartFake
    implements _i3.ExpertCatalogExpert {
  _FakeExpertCatalogExpert_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertCatalogTeam_3 extends _i1.SmartFake
    implements _i3.ExpertCatalogTeam {
  _FakeExpertCatalogTeam_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i4.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.WsConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStateStream),
        returnValue: _i5.Stream<_i6.WsConnectionState>.empty(),
      ) as _i5.Stream<_i6.WsConnectionState>);

  @override
  _i6.WsConnectionState get connectionState => (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i6.WsConnectionState.disconnected,
      ) as _i6.WsConnectionState);

  @override
  _i5.Future<void> reconnect() => (super.noSuchMethod(
        Invocation.method(
          #reconnect,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> ensureConnected({
    required String? userId,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureConnected,
          [],
          {
            #userId: userId,
            #token: token,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.ChatResponseModel> sendMessageToTask(
    String? taskId,
    String? message,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageToTask,
          [
            taskId,
            message,
            conversationId,
          ],
        ),
        returnValue:
            _i5.Future<_i2.ChatResponseModel>.value(_FakeChatResponseModel_0(
          this,
          Invocation.method(
            #sendMessageToTask,
            [
              taskId,
              message,
              conversationId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ChatResponseModel>);

  @override
  _i5.Future<List<_i7.ChatMessageModel>> getConversationHistory(
    String? conversationId, {
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationHistory,
          [conversationId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i7.ChatMessageModel>>.value(
            <_i7.ChatMessageModel>[]),
      ) as _i5.Future<List<_i7.ChatMessageModel>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRecentConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentConversations,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.MultiAgentCatalog> getMultiAgentCatalog() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMultiAgentCatalog,
          [],
        ),
        returnValue:
            _i5.Future<_i3.MultiAgentCatalog>.value(_FakeMultiAgentCatalog_1(
          this,
          Invocation.method(
            #getMultiAgentCatalog,
            [],
          ),
        )),
      ) as _i5.Future<_i3.MultiAgentCatalog>);

  @override
  _i5.Future<_i3.ExpertCatalogExpert> createCustomExpert({
    required String? name,
    required String? description,
    required String? systemPrompt,
    String? baseExpertId,
    String? preferredModelKey,
    String? reasoningMode = r'balanced',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomExpert,
          [],
          {
            #name: name,
            #description: description,
            #systemPrompt: systemPrompt,
            #baseExpertId: baseExpertId,
            #preferredModelKey: preferredModelKey,
            #reasoningMode: reasoningMode,
          },
        ),
        returnValue: _i5.Future<_i3.ExpertCatalogExpert>.value(
            _FakeExpertCatalogExpert_2(
          this,
          Invocation.method(
            #createCustomExpert,
            [],
            {
              #name: name,
              #description: description,
              #systemPrompt: systemPrompt,
              #baseExpertId: baseExpertId,
              #preferredModelKey: preferredModelKey,
              #reasoningMode: reasoningMode,
            },
          ),
        )),
      ) as _i5.Future<_i3.ExpertCatalogExpert>);

  @override
  _i5.Future<_i3.ExpertCatalogTeam> createCustomTeam({
    required String? name,
    required List<String>? expertIds,
    required List<String>? answerExpertIds,
    required String? collaborationMode,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomTeam,
          [],
          {
            #name: name,
            #expertIds: expertIds,
            #answerExpertIds: answerExpertIds,
            #collaborationMode: collaborationMode,
            #description: description,
          },
        ),
        returnValue:
            _i5.Future<_i3.ExpertCatalogTeam>.value(_FakeExpertCatalogTeam_3(
          this,
          Invocation.method(
            #createCustomTeam,
            [],
            {
              #name: name,
              #expertIds: expertIds,
              #answerExpertIds: answerExpertIds,
              #collaborationMode: collaborationMode,
              #description: description,
            },
          ),
        )),
      ) as _i5.Future<_i3.ExpertCatalogTeam>);

  @override
  _i5.Stream<_i8.ChatStreamEvent> chatStream(
    String? message,
    String? conversationId, {
    String? userId,
    String? requestId,
    String? nickname,
    Map<String, dynamic>? extraContext,
    String? token,
    List<String>? fileIds,
    bool? includeReferences = false,
    String? chatMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatStream,
          [
            message,
            conversationId,
          ],
          {
            #userId: userId,
            #requestId: requestId,
            #nickname: nickname,
            #extraContext: extraContext,
            #token: token,
            #fileIds: fileIds,
            #includeReferences: includeReferences,
            #chatMode: chatMode,
          },
        ),
        returnValue: _i5.Stream<_i8.ChatStreamEvent>.empty(),
      ) as _i5.Stream<_i8.ChatStreamEvent>);

  @override
  void sendActionFeedback({
    required String? action,
    required String? toolResultId,
    required String? widgetType,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendActionFeedback,
          [],
          {
            #action: action,
            #toolResultId: toolResultId,
            #widgetType: widgetType,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendInterventionFeedback({
    required String? requestId,
    required String? feedbackType,
    Map<String, dynamic>? extraData,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendInterventionFeedback,
          [],
          {
            #requestId: requestId,
            #feedbackType: feedbackType,
            #extraData: extraData,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendResponseFeedback({
    required String? responseId,
    required String? feedbackType,
    List<String>? reasons,
    String? freeText,
    String? workflowId,
    String? promptVersion,
    String? traceId,
    Map<String, dynamic>? meta,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendResponseFeedback,
          [],
          {
            #responseId: responseId,
            #feedbackType: feedbackType,
            #reasons: reasons,
            #freeText: freeText,
            #workflowId: workflowId,
            #promptVersion: promptVersion,
            #traceId: traceId,
            #meta: meta,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendPlanReviewFeedback({
    required String? reviewId,
    required String? userDecision,
    String? planId,
    String? userComment,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendPlanReviewFeedback,
          [],
          {
            #reviewId: reviewId,
            #userDecision: userDecision,
            #planId: planId,
            #userComment: userComment,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i8.ChatStreamEvent> chatStreamSSE(
    String? message,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatStreamSSE,
          [
            message,
            conversationId,
          ],
        ),
        returnValue: _i5.Stream<_i8.ChatStreamEvent>.empty(),
      ) as _i5.Stream<_i8.ChatStreamEvent>);
}
