// Mocks generated by Mockito 5.4.4 from annotations
// in sparkle/test/features/task/presentation/providers/task_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sparkle/features/task/data/models/execution_intent_model.dart'
    as _i4;
import 'package:sparkle/features/task/data/models/execution_record_model.dart'
    as _i5;
import 'package:sparkle/features/task/data/models/execution_template_model.dart'
    as _i10;
import 'package:sparkle/features/task/data/models/next_action.dart' as _i14;
import 'package:sparkle/features/task/data/models/next_action_selection_submission.dart'
    as _i13;
import 'package:sparkle/features/task/data/models/task_completion_result.dart'
    as _i7;
import 'package:sparkle/features/task/data/models/task_feedback_response.dart'
    as _i12;
import 'package:sparkle/features/task/data/models/task_feedback_submission.dart'
    as _i11;
import 'package:sparkle/features/task/data/models/task_nudge.dart' as _i6;
import 'package:sparkle/features/task/data/repositories/task_repository.dart'
    as _i8;
import 'package:sparkle/shared/entities/task_model.dart' as _i3;
import 'package:sparkle/shared/models/api_response_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskModel_1 extends _i1.SmartFake implements _i3.TaskModel {
  _FakeTaskModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExecutionIntentModel_2 extends _i1.SmartFake
    implements _i4.ExecutionIntentModel {
  _FakeExecutionIntentModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExecutionRecordModel_3 extends _i1.SmartFake
    implements _i5.ExecutionRecordModel {
  _FakeExecutionRecordModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskCreateResult_4 extends _i1.SmartFake
    implements _i6.TaskCreateResult {
  _FakeTaskCreateResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskCompletionResult_5 extends _i1.SmartFake
    implements _i7.TaskCompletionResult {
  _FakeTaskCompletionResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskSuggestionResponse_6 extends _i1.SmartFake
    implements _i3.TaskSuggestionResponse {
  _FakeTaskSuggestionResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i8.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.PaginatedResponse<_i3.TaskModel>> getTasks({
    Map<String, dynamic>? filters,
    int? page = 1,
    int? pageSize = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
          {
            #filters: filters,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i3.TaskModel>>.value(
            _FakePaginatedResponse_0<_i3.TaskModel>(
          this,
          Invocation.method(
            #getTasks,
            [],
            {
              #filters: filters,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i3.TaskModel>>);

  @override
  _i9.Future<_i3.TaskModel> getTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [id],
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #getTask,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<_i4.ExecutionIntentModel> handoffTask(
    String? taskId, {
    String? goal,
    List<String>? instructions,
    String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handoffTask,
          [taskId],
          {
            #goal: goal,
            #instructions: instructions,
            #templateId: templateId,
          },
        ),
        returnValue: _i9.Future<_i4.ExecutionIntentModel>.value(
            _FakeExecutionIntentModel_2(
          this,
          Invocation.method(
            #handoffTask,
            [taskId],
            {
              #goal: goal,
              #instructions: instructions,
              #templateId: templateId,
            },
          ),
        )),
      ) as _i9.Future<_i4.ExecutionIntentModel>);

  @override
  _i9.Future<List<_i10.ExecutionTemplateModel>> listExecutionTemplates(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listExecutionTemplates,
          [taskId],
        ),
        returnValue: _i9.Future<List<_i10.ExecutionTemplateModel>>.value(
            <_i10.ExecutionTemplateModel>[]),
      ) as _i9.Future<List<_i10.ExecutionTemplateModel>>);

  @override
  _i9.Future<List<_i4.ExecutionIntentModel>> listExecutionIntents(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listExecutionIntents,
          [taskId],
        ),
        returnValue: _i9.Future<List<_i4.ExecutionIntentModel>>.value(
            <_i4.ExecutionIntentModel>[]),
      ) as _i9.Future<List<_i4.ExecutionIntentModel>>);

  @override
  _i9.Future<_i5.ExecutionRecordModel?> getExecutionRecord(String? intentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExecutionRecord,
          [intentId],
        ),
        returnValue: _i9.Future<_i5.ExecutionRecordModel?>.value(),
      ) as _i9.Future<_i5.ExecutionRecordModel?>);

  @override
  _i9.Future<_i5.ExecutionRecordModel> confirmExecutionResult(
          String? recordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmExecutionResult,
          [recordId],
        ),
        returnValue: _i9.Future<_i5.ExecutionRecordModel>.value(
            _FakeExecutionRecordModel_3(
          this,
          Invocation.method(
            #confirmExecutionResult,
            [recordId],
          ),
        )),
      ) as _i9.Future<_i5.ExecutionRecordModel>);

  @override
  _i9.Future<_i5.ExecutionRecordModel> rejectExecutionResult(
    String? recordId, {
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectExecutionResult,
          [recordId],
          {#reason: reason},
        ),
        returnValue: _i9.Future<_i5.ExecutionRecordModel>.value(
            _FakeExecutionRecordModel_3(
          this,
          Invocation.method(
            #rejectExecutionResult,
            [recordId],
            {#reason: reason},
          ),
        )),
      ) as _i9.Future<_i5.ExecutionRecordModel>);

  @override
  _i9.Future<List<_i3.TaskModel>> getTodayTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTodayTasks,
          [],
        ),
        returnValue: _i9.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i9.Future<List<_i3.TaskModel>>);

  @override
  _i9.Future<List<_i3.TaskModel>> getRecommendedTasks({int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedTasks,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i9.Future<List<_i3.TaskModel>>);

  @override
  _i9.Future<List<_i3.TaskModel>> getTasksByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i9.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i9.Future<List<_i3.TaskModel>>);

  @override
  _i9.Future<_i3.TaskModel> createTask(
    _i3.TaskCreate? task, {
    bool? generateGuide = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
          {#generateGuide: generateGuide},
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #createTask,
            [task],
            {#generateGuide: generateGuide},
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<_i6.TaskCreateResult> createTaskWithNudges(
    _i3.TaskCreate? task, {
    bool? generateGuide = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTaskWithNudges,
          [task],
          {#generateGuide: generateGuide},
        ),
        returnValue:
            _i9.Future<_i6.TaskCreateResult>.value(_FakeTaskCreateResult_4(
          this,
          Invocation.method(
            #createTaskWithNudges,
            [task],
            {#generateGuide: generateGuide},
          ),
        )),
      ) as _i9.Future<_i6.TaskCreateResult>);

  @override
  _i9.Future<_i3.TaskModel> updateTask(
    String? id,
    _i3.TaskUpdate? task,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [
            id,
            task,
          ],
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #updateTask,
            [
              id,
              task,
            ],
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.TaskModel>> reorderTasks(List<String>? taskIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderTasks,
          [taskIds],
        ),
        returnValue: _i9.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i9.Future<List<_i3.TaskModel>>);

  @override
  _i9.Future<_i3.TaskModel> generateGuide(String? id) => (super.noSuchMethod(
        Invocation.method(
          #generateGuide,
          [id],
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #generateGuide,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<_i3.TaskModel> startTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #startTask,
          [id],
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #startTask,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<_i7.TaskCompletionResult> completeTask(
    String? id,
    int? actualMinutes,
    String? note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [
            id,
            actualMinutes,
            note,
          ],
        ),
        returnValue: _i9.Future<_i7.TaskCompletionResult>.value(
            _FakeTaskCompletionResult_5(
          this,
          Invocation.method(
            #completeTask,
            [
              id,
              actualMinutes,
              note,
            ],
          ),
        )),
      ) as _i9.Future<_i7.TaskCompletionResult>);

  @override
  _i9.Future<_i3.TaskModel> abandonTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #abandonTask,
          [id],
        ),
        returnValue: _i9.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #abandonTask,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.TaskModel>);

  @override
  _i9.Future<_i3.TaskSuggestionResponse> getSuggestions(String? inputText) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [inputText],
        ),
        returnValue: _i9.Future<_i3.TaskSuggestionResponse>.value(
            _FakeTaskSuggestionResponse_6(
          this,
          Invocation.method(
            #getSuggestions,
            [inputText],
          ),
        )),
      ) as _i9.Future<_i3.TaskSuggestionResponse>);

  @override
  _i9.Future<void> submitTaskFeedback(
    String? taskId,
    _i11.TaskFeedbackSubmission? feedback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitTaskFeedback,
          [
            taskId,
            feedback,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i12.TaskFeedbackResponse?> submitTaskFeedbackWithResponse(
    String? taskId,
    _i11.TaskFeedbackSubmission? feedback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitTaskFeedbackWithResponse,
          [
            taskId,
            feedback,
          ],
        ),
        returnValue: _i9.Future<_i12.TaskFeedbackResponse?>.value(),
      ) as _i9.Future<_i12.TaskFeedbackResponse?>);

  @override
  _i9.Future<void> submitReflectionAnswer(
    String? feedbackId, {
    String? selectedOption,
    String? freeText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReflectionAnswer,
          [feedbackId],
          {
            #selectedOption: selectedOption,
            #freeText: freeText,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> recordNextActionSelection(
    String? taskId,
    _i13.NextActionSelectionSubmission? selection,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordNextActionSelection,
          [
            taskId,
            selection,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> recordNextActionsSkip(
    String? taskId,
    List<_i14.NextAction>? actions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordNextActionsSkip,
          [
            taskId,
            actions,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>> confirmGeneratedTasks(
          String? toolResultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmGeneratedTasks,
          [toolResultId],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);
}
