#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

# Python protobuf stubs are generated at backend/app/gen/*.py, while runtime
# imports still use versioned packages such as app.gen.agent.v1. Mirror the
# generated root-level stubs into the package paths the backend imports.
SYNC_MAP = {
    "backend/app/gen/agent_service_pb2.py": "backend/app/gen/agent/v1/agent_service_pb2.py",
    "backend/app/gen/agent_service_pb2_grpc.py": "backend/app/gen/agent/v1/agent_service_pb2_grpc.py",
    "backend/app/gen/galaxy_service_pb2.py": "backend/app/gen/galaxy/v1/galaxy_service_pb2.py",
    "backend/app/gen/galaxy_service_pb2_grpc.py": "backend/app/gen/galaxy/v1/galaxy_service_pb2_grpc.py",
    "backend/app/gen/stt_service_pb2.py": "backend/app/gen/stt/v1/stt_service_pb2.py",
    "backend/app/gen/stt_service_pb2_grpc.py": "backend/app/gen/stt/v1/stt_service_pb2_grpc.py",
    "backend/app/gen/user_state_pb2.py": "backend/app/gen/userstate/v1/user_state_pb2.py",
    "backend/app/gen/user_state_pb2.pyi": "backend/app/gen/userstate/v1/user_state_pb2.pyi",
    "backend/app/gen/websocket_pb2.py": "backend/app/gen/ws/websocket_pb2.py",
    "backend/app/gen/websocket_pb2.pyi": "backend/app/gen/ws/websocket_pb2.pyi",
}

# Map of structured _pb2.py files that should become re-export stubs instead of
# copies. Flat files are the originals (generated by protoc) and use bare imports
# (e.g. `import agent_service_pb2`) that require the flat files to have real proto
# code. Structured files can re-export from flat to avoid registering the same proto
# twice in the protobuf descriptor pool, which causes TypeError on import.
PB2_REEXPORT_MAP = {
    "backend/app/gen/agent/v1/agent_service_pb2.py": "app.gen.agent_service_pb2",
    "backend/app/gen/galaxy/v1/galaxy_service_pb2.py": "app.gen.galaxy_service_pb2",
    "backend/app/gen/stt/v1/stt_service_pb2.py": "app.gen.stt_service_pb2",
    "backend/app/gen/userstate/v1/user_state_pb2.py": "app.gen.user_state_pb2",
}


def _write_reexport(target_path: Path, flat_import: str) -> None:
    """Replace a structured proto file with a re-export stub from the flat version."""
    reexport = (
        f"# -*- coding: utf-8 -*-\n"
        f"# Re-export from flat generated path to avoid descriptor pool conflicts.\n"
        f"# The canonical generated source is the flat file at app/gen/.\n"
        f"from {flat_import} import *  # noqa: F401,F403\n"
    )
    target_path.write_text(reexport)


def main() -> int:
    copied = 0
    for source_rel, target_rel in SYNC_MAP.items():
        source = REPO_ROOT / source_rel
        target = REPO_ROOT / target_rel
        if not source.exists():
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copied += 1

    # Convert structured _pb2.py files to re-export stubs so only the flat
    # versions register protos in the descriptor pool.
    reexports = 0
    for structured_rel, flat_import in PB2_REEXPORT_MAP.items():
        structured_path = REPO_ROOT / structured_rel
        if structured_path.exists() and structured_rel.endswith("_pb2.py"):
            _write_reexport(structured_path, flat_import)
            reexports += 1

    print(f"Synced {copied} Python protobuf runtime stubs, converted {reexports} structured to re-exports.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
