#!/usr/bin/env python3
"""
批量翻译 app_zh.arb 中未翻译的英文字符串
"""

import json
import re

# 翻译映射表 - 基于键名的语义翻译
TRANSLATIONS = {
    # Token 相关
    "chatPromptTokens": "提示词 Token",
    "chatCompletionTokens": "补全 Token",

    # 记忆相关
    "memoryCorrectionReject": "不正确",
    "memoryCorrectionNoLongerApplies": "不再适用",
    "memoryCorrectionLowerConfidence": "置信度较低",
    "memoryCorrectionMerge": "合并",
    "memoryWhyThisMemory": "为什么有这条记忆？",
    "memoryEvidenceCount": "证据数",
    "memoryVersions": "版本数",
    "memoryBudget": "预算",
    "memoryExplanationPreference": "已记录，因为您的偏好最近更新了。",
    "memoryExplanationEpisodic": "已记录，因为这段经历被标记为重要。",
    "memoryExplanationGoal": "已记录，以保持您的活跃目标可见。",

    # 聊天动作相关
    "chatActionErrorTitle": "操作错误",
    "chatActionIgnore": "忽略",
    "chatActionLater": "稍后",
    "chatActionReviewed": "已审阅",
    "chatActionStatusCompleted": "已完成",
    "chatActionStatusConfirmed": "已确认",
    "chatActionStatusDismissed": "已忽略",
    "chatActionStatusFailed": "失败",
    "chatActionStatusProcessing": "处理中",
    "chatActionTitleAddError": "添加错误",
    "chatActionTitleBlockedInput": "输入被阻止",
    "chatActionTitleContinuity": "延续性",
    "chatActionTitleCreatePlan": "创建计划",
    "chatActionTitleCreateTask": "创建任务",
    "chatActionTitleDefault": "默认标题",
    "chatActionTitleEvolution": "演进",
    "chatActionTitleExecutionSummary": "执行摘要",
    "chatActionTitleFocusSprint": "专注冲刺",
    "chatActionTitleModeExplanation": "模式说明",
    "chatActionTitleNextActions": "下一步行动",
    "chatActionTitleNightlyReview": "夜间回顾",
    "chatActionTitleProgress": "进度",
    "chatActionTitleReflection": "反思",
    "chatActionTitleSourceSummary": "来源摘要",
    "chatActionTitleSystemUpdate": "系统更新",
    "chatActionTitleTaskList": "任务列表",
    "chatActionTitleUpdatePreference": "更新偏好",
    "chatActionViewNextSteps": "查看下一步",
    "chatActionViewSources": "查看来源",
    "chatAgentRouting": "智能路由",
    "chatAuthExpired": "认证已过期",
    "chatAuthRefreshing": "正在刷新认证",
    "chatBlockedInputTitle": "输入已阻止",
    "chatCollabTimelineTitle": "协作时间线",
    "chatComparisonAfter": "之后",
    "chatComparisonBefore": "之前",
    "chatCompletionBlocked": "补全已阻止",
    "chatCompletionDone": "补全完成",
    "chatCompletionNeedsInput": "需要输入",
    "chatCompletionPartial": "部分完成",
    "chatCompletionProcessing": "处理中",
    "chatConfidenceCautious": "谨慎",
    "chatConfidenceHigh": "高",
    "chatConfidenceMedium": "中",
    "chatConfirmationActionDefault": "确认操作",
    "chatConfirmationConfirmUpdate": "确认更新",
    "chatConfirmationTitleDefault": "确认",
    "chatConfirmationTitleUpdatePreference": "确认更新偏好",
    "chatConfirmationUpdatePreferenceGeneric": "更新偏好设置",
    "chatCopiedToClipboard": "已复制到剪贴板",
    "chatDagExecutionAbortedDefault": "执行已中止",
    "chatDagExecutionCompleted": "执行已完成",
    "chatDagExecutionEndAbortedDefault": "执行已中止",
    "chatDagStepFallback": "步骤回退",
    "chatEvolutionHeadlineDefault": "演进过程",
    "chatExecutionCompleted": "执行完成",
    "chatExecutionFailed": "执行失败",
    "chatExecutionPartial": "部分执行",
    "chatFeedbackThanks": "感谢您的反馈！",
    "chatFocusSprintDefaultTitle": "专注冲刺",
    "chatFocusStart": "开始专注",
    "chatInputDocumentClean": "清理文档",
    "chatInterventionViewPlan": "查看计划",
    "chatInterventionViewSettings": "查看设置",
    "chatKnowledgeCitationBody": "知识引用",
    "chatModeCustomTeam": "自定义团队",
    "chatModeCustomTeamDesc": "选择特定的 AI 助手组成您的专属团队",
    "chatModeKeepCurrent": "保持当前模式",
    "chatModeSuggestionTitle": "模式建议",
    "chatModeSwitch": "切换模式",
    "chatMultiAgentCollab": "多智能体协作",
    "chatNextActionsRetryHint": "点击重试",
    "chatNextActionsTitle": "下一步行动",
    "chatNightlyReviewTodos": "夜间待办",
    "chatNotificationGroupMessage": "群组消息",
    "chatNotificationMention": "有人@我",
    "chatOptionalNotesHint": "可选备注...",
    "chatOrchestrationTraceStep": "编排步骤",
    "chatOrchestrationTraceTitle": "编排追踪",
    "chatPlanContextClear": "清除上下文",
    "chatPlanContextSelect": "选择计划上下文",
    "chatPlanEmptySubtitle": "还没有计划，开始创建一个吧",
    "chatPlanEmptyTitle": "暂无计划",
    "chatPlanReviewAcknowledged": "已确认",
    "chatPlanReviewApproved": "已批准",
    "chatPlanReviewModifyRequested": "请求修改",
    "chatPlanReviewRejected": "已拒绝",
    "chatPlanSelect": "选择计划",
    "chatReasoningProcess": "推理过程",
    "chatReasoningStatusAnalyzing": "正在分析...",
    "chatReasoningStatusAudioProcessing": "正在处理音频...",
    "chatReasoningStatusCalculating": "正在计算...",
    "chatReasoningStatusCoding": "正在编程...",
    "chatReasoningStatusDataAnalyzing": "正在分析数据...",
    "chatReasoningStatusDone": "完成",
    "chatReasoningStatusImageProcessing": "正在处理图像...",
    "chatReasoningStatusPlanning": "正在规划...",
    "chatReasoningStatusPreparing": "正在准备...",
    "chatReasoningStatusReasoning": "正在推理...",
    "chatReasoningStatusRetrieving": "正在检索...",
    "chatReasoningStatusSearching": "正在搜索...",
    "chatReasoningStatusTranslating": "正在翻译...",
    "chatReasoningStatusWriting": "正在撰写...",
    "chatReflectionDegraded": "反思质量下降",
    "chatReflectionFailed": "反思失败",
    "chatReflectionNoChange": "无需变更",
    "chatSourceUnknown": "未知来源",
    "chatSourceUntitled": "无标题",
    "chatSourcesAvailable": "有可用来源",
    "chatSourcesUnavailable": "无可用来源",
    "chatSubmitFeedback": "提交反馈",
    "chatSynthesisSuggestions": "综合建议",
    "chatViewComparisonData": "查看对比数据",
    "chatViewPlanRationale": "查看计划依据",
    "chatVoiceNoMicPermission": "没有麦克风权限",
    "chatWorkflowDebateProcessing": "辩论处理中...",
    "chatWorkflowDebateSubtitle": "多角度探讨",
    "chatWorkflowDebateTitle": "辩论模式",
    "chatWorkflowDefault": "默认工作流",
    "chatWorkflowDelegationSubtitle": "委派给专业助手",
    "chatWorkflowDelegationTitle": "委派模式",
    "chatWorkflowErrorDiagnosis": "错误诊断",
    "chatWorkflowExpertRouting": "专家路由",
    "chatWorkflowParallelSubtitle": "并行处理多个任务",
    "chatWorkflowProgressiveExploration": "渐进式探索",
    "chatWorkflowStatusActive": "活跃",
    "chatWorkflowStatusDone": "完成",
    "chatWorkflowStatusError": "错误",
    "chatWorkflowStatusWaiting": "等待中",
    "chatWorkflowTaskDecomposition": "任务分解",
    "commonMinutesShort": "分钟",
    "commonUnknown": "未知",

    # 社区相关
    "communityAgentCollabOff": "AI 协作已关闭",
    "communityAgentCollabOn": "AI 协作已开启",
    "communityAgentOnlyYou": "只有你在群里",
    "communityAgentProcessing": "AI 正在处理...",
    "communityAgentPromptHint": "输入提示词...",
    "communityAgentQuickConsensus": "快速共识",
    "communityAgentQuickConsensusPrompt": "帮我快速总结群内共识",
    "communityAgentQuickReminder": "快速提醒",
    "communityAgentQuickReminderPrompt": "帮我设置一个提醒",
    "communityAgentQuickSummary": "快速总结",
    "communityAgentQuickSummaryPrompt": "帮我总结最近的讨论",
    "communityAgentThinking": "AI 思考中...",
    "communityChatEmpty": "暂无消息",
    "communityChatTitle": "社群聊天",
    "communityCheckInAction": "打卡",
    "communityCheckInDurationLabel": "时长",
    "communityCheckInMessageHint": "分享你的心得...",
    "communityCheckInMessageLabel": "打卡内容",
    "communityCheckInSuccess": "打卡成功！",
    "communityCheckInTitle": "每日打卡",
    "communityFileSharedSuccess": "文件分享成功",
    "communityGroupFiles": "群文件",
    "communityMessageFallback": "消息加载中...",
    "communityMessageInputHint": "输入消息...",
    "communitySearchGroupMessages": "搜索群消息",

    # 文件状态
    "fileStatusFailed": "上传失败",
    "fileStatusProcessing": "处理中",
    "fileStatusReady": "就绪",
    "fileStatusUploaded": "已上传",

    # 知识星图相关
    "galaxyA11yActionStartLearning": "开始学习",
    "galaxyA11yActionUnlockNode": "解锁节点",
    "galaxyA11yHintStartLearning": "点击开始学习此知识点",
    "galaxyA11yHintUnlockNode": "点击解锁此节点",
    "galaxyA11yNavigationHint": "使用手势导航知识星图",
    "galaxyA11yNodeLocked": "节点已锁定",
    "galaxyA11yNodeUnlocked": "节点已解锁",
    "galaxyControlOverview": "概览",
    "galaxyControlReplayStart": "开始回放",
    "galaxyControlReplayStop": "停止回放",
    "galaxyControlSearchClose": "关闭搜索",
    "galaxyControlSearchOpen": "打开搜索",
    "galaxyControlSettings": "设置",
    "galaxyControlZoomIn": "放大",
    "galaxyControlZoomOut": "缩小",
    "galaxyEmptyMessage": "开始探索，点亮你的知识星图",
    "galaxyEmptyTitle": "星图空空如也",
    "galaxyErrorConnectionFailed": "连接失败",
    "galaxyErrorConnectionTimeout": "连接超时",
    "galaxyErrorLoadFailed": "加载失败",
    "galaxyErrorNetwork": "网络错误",
    "galaxyErrorNetworkFailed": "网络请求失败",
    "galaxyErrorRequestFailed": "请求失败",
    "galaxyErrorResponseTimeout": "响应超时",
    "galaxyErrorRetryHint": "点击重试",
    "galaxyErrorServiceTemporarilyUnavailable": "服务暂时不可用",
    "galaxyErrorServiceUnavailable": "服务不可用",
    "galaxyErrorUnknown": "未知错误",
    "galaxyGraphRagGraph": "图谱检索",
    "galaxyGraphRagSearching": "正在检索...",
    "galaxyGraphRagTime": "时间",
    "galaxyGraphRagVector": "向量检索",
    "galaxyImportanceAdvanced": "进阶",
    "galaxyImportanceBasic": "基础",
    "galaxyImportanceCore": "核心",
    "galaxyImportanceEntry": "入门",
    "galaxyImportanceIntermediate": "中级",
    "galaxyImportanceNormal": "普通",
    "galaxyLoadFailed": "加载失败",
    "galaxyLoadFailedTitle": "星图加载失败",
    "galaxyLoadingMessage": "正在加载星图...",
    "galaxyLoadingTitle": "加载中",
    "galaxyNodeFocus": "聚焦节点",
    "galaxyNodeInspectConnections": "查看连接",
    "galaxyNodeLocked": "已锁定",
    "galaxyNodeUnlocked": "已解锁",
    "galaxyOfflineMode": "离线模式",
    "galaxyOverviewMastery": "掌握度",
    "galaxyOverviewNodes": "节点数",
    "galaxyOverviewUnlocked": "已解锁",
    "galaxyPerfRecommendationDisableParticles": "禁用粒子效果",
    "galaxyPerfRecommendationLowQualityMode": "低质量模式",
    "galaxyPerfRecommendationOptimizeLayout": "优化布局",
    "galaxyPerfRecommendationReduceNodes": "减少显示节点",
    "galaxyPerfStatusCritical": "性能严重不足",
    "galaxyPerfStatusDegraded": "性能下降",
    "galaxyPerfStatusOptimal": "性能最佳",
    "galaxyReload": "重新加载",
    "galaxySearchHint": "搜索知识节点...",
    "galaxySearchHintDetail": "输入关键词搜索",
    "galaxySearchNoResults": "未找到相关节点",
    "galaxySearchTitle": "搜索星图",
    "galaxySectorArt": "艺术",
    "galaxySectorCivilization": "文明",
    "galaxySectorCosmos": "宇宙",
    "galaxySectorLife": "生命",
    "galaxySectorTech": "科技",
    "galaxySectorVoid": "虚空",
    "galaxySectorWisdom": "智慧",
    "galaxySimulationCenterGravity": "中心引力",
    "galaxySimulationGravity": "引力",
    "galaxySimulationReplaySpeed": "回放速度",
    "galaxySimulationRepulsion": "斥力",
    "galaxySimulationReset": "重置",
    "galaxySimulationSubtitle": "调整物理参数",
    "galaxySimulationTitle": "模拟设置",
    "galaxyUsingCache": "使用缓存数据",

    # 密码设置
    "passwordSetConfirm": "确认设置密码",
    "passwordSetHint": "请输入至少8位密码",
    "passwordSetLabel": "设置密码",
    "passwordSetSuccess": "密码设置成功",
    "passwordSetTitle": "设置密码",

    # 计划相关
    "planArchive": "归档计划",
    "planArchiveConfirm": "确认归档",
    "planArchiveMessage": "归档后计划将移至历史记录，确定要归档吗？",
    "planArchiveTitle": "归档计划",
    "planArchivedSuccess": "计划已归档",
    "planContextTitle": "计划上下文",
    "planDetailTitle": "计划详情",
    "planDueToday": "今日到期",
    "planKeyFacts": "关键事实",
    "planNoContent": "暂无内容",
    "planNoTasks": "暂无任务",
    "planNoVisualizationData": "暂无可视化数据",
    "planProgressLabel": "计划进度",
    "planRecentFeedback": "最近反馈",
    "planRelatedTasks": "相关任务",
    "planRestore": "恢复计划",
    "planRestoredSuccess": "计划已恢复",
    "planReviewAdditionalNotesHint": "添加备注（可选）...",
    "planReviewAdditionalNotesRequired": "请填写备注",
    "planReviewApproveExecute": "批准并执行",
    "planReviewConfidenceTitle": "置信度评估",
    "planReviewDecisionApproved": "已批准",
    "planReviewDecisionNeedsModification": "需要修改",
    "planReviewDecisionRejected": "已拒绝",
    "planReviewDecisionRequiresConfirmation": "需要确认",
    "planReviewModifyPlan": "修改计划",
    "planReviewReasonDifficultyTooHigh": "难度过高",
    "planReviewReasonDifficultyTooLow": "难度过低",
    "planReviewReasonMissingKeyTask": "缺少关键任务",
    "planReviewReasonOther": "其他原因",
    "planReviewReasonScheduleUnreasonable": "时间安排不合理",
    "planReviewReasonTasksTooFew": "任务太少",
    "planReviewReasonTasksTooMany": "任务太多",
    "planReviewRejectReasonTitle": "拒绝原因",
    "planReviewRejectWithFeedback": "拒绝并反馈",
    "planReviewSelectReasonRequired": "请选择原因",
    "planReviewSubmitFeedback": "提交反馈",
    "planReviewSummaryApproved": "计划已批准",
    "planReviewSummaryNeedsModification": "计划需要修改",
    "planReviewSummaryRejected": "计划已拒绝",
    "planReviewSummaryRequiresConfirmation": "计划需要确认",
    "planSectionCompletionRate": "完成率",
    "planSectionDailyCompletion": "每日完成情况",
    "planSectionTaskTypeDistribution": "任务类型分布",
    "planShare": "分享计划",
    "planStatusActive": "进行中",
    "planStatusArchived": "已归档",
    "planStatusCompleted": "已完成",
    "planStatusPaused": "已暂停",
    "planStatusUnknown": "未知状态",
    "planTabOverview": "概览",
    "planTabProgress": "进度",
    "planTaskProgress": "任务进度",
    "planUpcomingTasks": "即将到来的任务",

    # 番茄钟
    "pomodoroBreakFinished": "休息结束！",
    "pomodoroWorkFinished": "工作完成！",

    # 重新生成
    "regenCustomHint": "描述你想要的修改...",
    "regenDescCompleted": "重新生成完成",
    "regenDescFailed": "重新生成失败",
    "regenDescInProgress": "正在重新生成...",
    "regenDescPending": "等待重新生成",
    "regenHintAddExamples": "添加更多示例",
    "regenHintFixErrors": "修正错误",
    "regenHintFriendlierTone": "更友好的语气",
    "regenHintMoreAccurate": "更准确",
    "regenHintMoreConcise": "更简洁",
    "regenHintMoreDetailed": "更详细",
    "regenHintsOptional": "可选提示",
    "regenImprovementsTitle": "改进建议",
    "regenProgressTitle": "重新生成进度",
    "regenResultFailed": "生成失败",
    "regenResultSuccess": "生成成功",
    "regenRetryMessage": "点击重试",
    "regenSelectType": "选择类型",
    "regenStart": "开始重新生成",
    "regenTitleCompleted": "重新生成完成",
    "regenTitleFailed": "重新生成失败",
    "regenTitleIdle": "等待操作",
    "regenTitleInProgress": "正在生成...",
    "regenTitlePending": "等待中",
    "regenTypeAddDetails": "添加细节",
    "regenTypeChangeStyle": "改变风格",
    "regenTypeCustom": "自定义",
    "regenTypeFixIssues": "修复问题",
    "regenTypeImproveQuality": "提高质量",
    "regenTypeSimplify": "简化",

    # 评价相关
    "reviewRatingAccuracyTitle": "准确性评价",
    "reviewRatingAccurate": "准确",
    "reviewRatingAddInaccuratePoint": "添加不准确点",
    "reviewRatingCommentsHint": "输入您的评价...",
    "reviewRatingCommentsTitle": "评价内容",
    "reviewRatingHelpful": "有帮助",
    "reviewRatingInaccurate": "不准确",
    "reviewRatingInaccuratePointHint": "描述不准确的地方...",
    "reviewRatingInaccuratePointsTitle": "不准确之处",
    "reviewRatingLessOptions": "收起选项",
    "reviewRatingMoreOptions": "更多选项",
    "reviewRatingNotHelpful": "没帮助",
    "reviewRatingSpecificityTitle": "具体性评价",
    "reviewRatingSubmit": "提交评价",
    "reviewRatingSubmitFailed": "提交失败",
    "reviewRatingSubmitSuccess": "评价提交成功",
    "reviewRatingSubtitle": "您的反馈将帮助我们改进",
    "reviewRatingTagsTitle": "选择标签",
    "reviewRatingTitle": "评价回复",
    "reviewSpecificityAppropriate": "恰当",
    "reviewSpecificityTooDetailed": "太详细",
    "reviewSpecificityTooVague": "太模糊",
    "reviewTagAccurate": "准确",
    "reviewTagClear": "清晰",
    "reviewTagNeedsImprovement": "需要改进",
    "reviewTagPractical": "实用",
    "reviewTagTooLenient": "太宽松",
    "reviewTagTooStrict": "太严格",

    # 冲刺相关
    "sprintActionAbandonButton": "放弃冲刺",
    "sprintActionAbandonSubtitle": "放弃当前冲刺",
    "sprintActionAbandonTitle": "放弃冲刺",
    "sprintActionCompleteButton": "完成冲刺",
    "sprintActionCompleteSubtitle": "标记冲刺为完成",
    "sprintActionCompleteTitle": "完成冲刺",
    "sprintActionExtendSubtitle": "延长冲刺时间",
    "sprintActionExtendTitle": "延长冲刺",
    "sprintActionsTitle": "冲刺操作",
    "sprintCompletedTasks": "已完成任务",
    "sprintCompletionRate": "完成率",
    "sprintConfirmAbandonDesc": "确定要放弃这个冲刺吗？未完成的任务将保留。",
    "sprintConfirmAbandonTitle": "确认放弃",
    "sprintConfirmCompleteDesc": "恭喜完成冲刺！确定要标记为完成吗？",
    "sprintConfirmCompleteTitle": "确认完成",
    "sprintDailyCompletion": "每日完成情况",
    "sprintDurationDaysLabel": "持续天数",
    "sprintDurationLabel": "持续时间",
    "sprintEndDateLabel": "结束日期",
    "sprintExtendSelectDays": "选择延长天数",
    "sprintExtendTitle": "延长冲刺",
    "sprintIncompleteTasks": "未完成任务",
    "sprintInfoTitle": "冲刺信息",
    "sprintOngoing": "进行中",
    "sprintProgressTitle": "冲刺进度",
    "sprintRemainingTasks": "剩余任务",
    "sprintStartDateLabel": "开始日期",
    "sprintStatsEmpty": "暂无统计数据",
    "sprintStatsTitle": "冲刺统计",
    "sprintStatusCompleted": "已完成",
    "sprintStatusInProgress": "进行中",
    "sprintStatusLabel": "冲刺状态",
    "sprintStatusTodo": "待开始",
    "sprintTaskSummaryTitle": "任务摘要",
    "sprintTotalTasks": "总任务数",

    # 状态
    "statusCompleted": "已完成",
    "statusFailed": "失败",
    "statusInProgress": "进行中",
    "statusPending": "待处理",

    # 任务相关
    "taskChatAssistantTitle": "任务助手",
    "taskChatEmptyPrompt": "有什么可以帮你的？",
    "taskChatInputHint": "输入消息...",
    "taskCreateAction": "创建任务",
    "taskCreateSuccess": "任务创建成功",
    "taskCreateTitle": "创建任务",
    "taskCreatedWithSuggestions": "已根据建议创建任务",
    "taskCreating": "正在创建任务...",
    "taskDeadline": "截止时间",
    "taskDeadlineLabel": "截止时间",
    "taskDeleteConfirm": "确定要删除这个任务吗？",
    "taskDeleteTitle": "删除任务",
    "taskDetailLoading": "加载任务详情...",
    "taskDifficulty": "难度",
    "taskDifficultyLabel": "难度",
    "taskEnergyCost": "精力消耗",
    "taskEnergyCostLabel": "精力消耗",
    "taskEstimatedDuration": "预计时长",
    "taskEstimatedDurationLabel": "预计时长",
    "taskExecutionAbandon": "放弃执行",
    "taskExecutionCompleteTitle": "完成任务",
    "taskExecutionCompletedTitle": "任务已完成",
    "taskExecutionConfirmComplete": "确认完成",
    "taskExecutionEnterFocus": "进入专注模式",
    "taskExecutionFeatureCoach": "专注教练",
    "taskExecutionFeatureDistraction": "分心检测",
    "taskExecutionFeatureFlipClock": "翻页时钟",
    "taskExecutionFeatureFullscreen": "全屏模式",
    "taskExecutionFeatureReward": "完成奖励",
    "taskExecutionFeatureStarfield": "星空背景",
    "taskExecutionGuideEmpty": "暂无执行指南",
    "taskExecutionGuideTitle": "执行指南",
    "taskExecutionNoTask": "当前没有执行中的任务",
    "taskExecutionNoteHint": "添加执行笔记...",
    "taskExecutionNoteLabel": "执行笔记",
    "taskExecutionSkipAnimation": "跳过动画",
    "taskExecutionStartNow": "立即开始",
    "taskExecutionSyncFailed": "同步失败",
    "taskExecutionTapToContinue": "点击继续",
    "taskExecutionTimerLabel": "计时器",
    "taskExitCancelStep1": "取消退出",
    "taskExitCancelStep2": "继续取消",
    "taskExitCancelStep3": "保留任务",
    "taskExitConfirmStep1": "确认退出",
    "taskExitConfirmStep2": "再次确认",
    "taskExitConfirmStep3": "放弃任务",
    "taskExitMessageStep1": "确定要退出吗？进度将丢失。",
    "taskExitMessageStep3": "任务已放弃，下次继续加油！",
    "taskExitTitleStep1": "退出任务",
    "taskExitTitleStep2": "再次确认",
    "taskExitTitleStep3": "已放弃",
    "taskGenerateGuideSubtitle": "AI 正在生成执行指南...",
    "taskGenerateGuideTitle": "生成执行指南",
    "taskGuideEmpty": "暂无指南",
    "taskGuideTitle": "任务指南",
    "taskListLoading": "加载任务列表...",
    "taskListTitle": "任务列表",
    "taskNudgeApply": "应用建议",
    "taskNudgeDismiss": "忽略",
    "taskNudgeTitle": "任务建议",
    "taskReminderEnableSubtitle": "开启任务提醒功能",
    "taskReminderEnableTitle": "开启提醒",
    "taskReminderInfoBody": "任务提醒会在截止时间前通知您",
    "taskReminderInfoTitle": "提醒说明",
    "taskReminderPermissionDenied": "没有通知权限",
    "taskReminderRefreshAll": "刷新所有提醒",
    "taskReminderRefreshSuccess": "提醒已刷新",
    "taskReminderSettingsTitle": "提醒设置",
    "taskReminderTimesTitle": "提醒时间",
    "taskSearchHint": "搜索任务...",
    "taskStart": "开始任务",
    "taskSuggestedKnowledge": "推荐知识",
    "taskTagsHint": "添加标签...",
    "taskTagsLabel": "标签",
    "taskTimerPomodoro": "番茄钟",
    "taskTitleHint": "输入任务标题...",
    "taskTitleLabel": "任务标题",
    "taskTitleRequired": "请输入任务标题",
    "taskTypeLabel": "任务类型",
    "taskTypeOcr": "OCR识别",
    "taskUntitled": "未命名任务",
    "taskViewAll": "查看全部",

    # 周日程
    "weeklyAgendaCollapsedHint": "展开查看完整周日程",
    "weeklyAgendaEmptyHint": "本周暂无日程安排",

    # 同步中心
    "syncCenterTopicLegacy": "旧版",
    "syncCenterTraceIdValue": "追踪ID：{value}",

    # 其他
    "memoryDiff": "差异",
    "memoryRevertNotEnabled": "回滚功能尚未启用",
}

def is_english_text(text):
    """检查文本是否是纯英文（需要翻译）"""
    # 排除已包含中文的文本
    if re.search(r'[\u4e00-\u9fff]', text):
        return False
    # 排除纯技术术语（如品牌名、专有名词）
    if text in ['Google', 'Apple', 'Sparkle', 'Ocean', 'Forest', 'English',
                'WebSocket', 'PostgreSQL', 'pgvector', 'Flutter', 'Python',
                'GraphRAG', 'Sprint', 'Growth Plan', 'Legacy', 'Token',
                'Prompt Tokens', 'Completion Tokens', 'Diff', 'AI', 'Lv.',
                'Qwen3', 'Go Gateway', 'Python Agent Engine']:
        return False
    # 检查是否是英文句子（包含空格的多个单词）
    if ' ' in text and re.match(r'^[A-Za-z0-9\s\.\,\!\?\:\;\-\+\(\)\[\]]+$', text):
        return True
    return False

def translate_file():
    """翻译文件中的英文字符串"""
    input_file = '/Users/brsama/code/GitHub/Sparkle-project/mobile/lib/l10n/app_zh.arb'

    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # 解析 JSON
    data = json.loads(content)

    translated_count = 0
    for key, value in data.items():
        # 跳过元数据字段
        if key.startswith('@'):
            continue
        if not isinstance(value, str):
            continue

        # 检查是否需要翻译
        if is_english_text(value) and key in TRANSLATIONS:
            data[key] = TRANSLATIONS[key]
            translated_count += 1
            print(f"✅ {key}: '{value}' -> '{TRANSLATIONS[key]}'")

    # 写回文件
    with open(input_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\n🎉 翻译完成！共翻译了 {translated_count} 个字符串")

if __name__ == '__main__':
    translate_file()
