"""
Core: <cognitive|execution|bridge|infra>
Phase: <sense|clarify|plan|execute|reflect|reinforce|adapt|none>
Stage: <首次引入 Stage 号>
"""

import time
from asyncio import iscoroutinefunction
from functools import wraps

from loguru import logger
from opentelemetry import trace
from prometheus_client import REGISTRY, Counter, Gauge, Histogram


def get_or_create_metric(metric_type, name, documentation, labelnames=(), **kwargs):
    """Safely get or create a prometheus metric."""
    if name in REGISTRY._names_to_collectors:
        return REGISTRY._names_to_collectors[name]
    return metric_type(name, documentation, labelnames, **kwargs)


# 1. 基础请求指标
REQUEST_COUNT = get_or_create_metric(
    Counter, "sparkle_requests_total", "Total number of requests", ["module", "method", "status"]
)

REQUEST_LATENCY = get_or_create_metric(
    Histogram, "sparkle_request_latency_seconds", "Request latency in seconds", ["module", "method"]
)

# 2. LLM 与 Token 指标
TOKEN_USAGE = get_or_create_metric(
    Counter,
    "sparkle_tokens_total",
    "Total number of tokens used",
    ["model", "type"],  # Removed user_id to prevent cardinality explosion
)

LLM_CALL_DURATION = get_or_create_metric(
    Histogram, "sparkle_llm_call_duration_seconds", "LLM call duration in seconds", ["model", "provider"]
)

AI_RESPONSE_TOTAL_DURATION = get_or_create_metric(
    Histogram,
    "sparkle_ai_response_total_duration_seconds",
    "End-to-end AI response duration in seconds",
    ["chat_mode", "reasoning_mode", "model_tier"],
    buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0, 55.0, 89.0],
)

AI_RESPONSE_FIRST_TOKEN_DURATION = get_or_create_metric(
    Histogram,
    "sparkle_ai_response_first_token_duration_seconds",
    "Time to first visible token/event for AI responses in seconds",
    ["chat_mode", "reasoning_mode"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0],
)

AI_RESPONSE_STREAM_DURATION = get_or_create_metric(
    Histogram,
    "sparkle_ai_response_stream_duration_seconds",
    "Streaming duration after first token/event in seconds",
    ["chat_mode", "reasoning_mode"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0],
)

AI_PREDICTION_DURATION = get_or_create_metric(
    Histogram,
    "sparkle_ai_prediction_duration_seconds",
    "Duration of AI/user-behavior prediction pipeline in seconds",
    ["source", "tier", "fallback"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0],
)

AI_PREDICTION_FALLBACK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_ai_prediction_fallback_total",
    "Prediction fallbacks by source transition",
    ["from_source", "to_source"],
)

COUNTERFACTUAL_REPORTS_GENERATED = get_or_create_metric(
    Counter,
    "sparkle_counterfactual_reports_generated_total",
    "Counterfactual evaluation reports generated by promotion status",
    ["status"],
)

COUNTERFACTUAL_EVIDENCE_GRADE = get_or_create_metric(
    Histogram,
    "sparkle_counterfactual_evidence_grade_histogram",
    "Evidence grade distribution for counterfactual evaluation reports",
    buckets=[0, 1, 2, 3, 4, 5, 6],
)

COUNTERFACTUAL_PROMOTION_PENDING = get_or_create_metric(
    Gauge,
    "sparkle_counterfactual_promotion_pending",
    "Counterfactual promotion candidates pending admin review",
)

COUNTERFACTUAL_EVALUATION_FAILURE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_counterfactual_evaluation_failures_total",
    "Counterfactual evaluation failures by source",
    ["source"],
)

# 3. 缓存指标
CACHE_HIT_COUNT = get_or_create_metric(
    Counter,
    "sparkle_cache_hits_total",
    "Total number of cache hits/misses",
    ["cache_name", "result"],  # result: hit, miss
)

SEMANTIC_CACHE_HIT_TOTAL = get_or_create_metric(
    Counter, "sparkle_semantic_cache_hit_total", "Total semantic cache hits"
)

SEMANTIC_CACHE_MISS_TOTAL = get_or_create_metric(
    Counter, "sparkle_semantic_cache_miss_total", "Total semantic cache misses"
)

SEMANTIC_CACHE_BYPASS_TOTAL = get_or_create_metric(
    Counter, "sparkle_semantic_cache_bypass_total", "Total semantic cache bypasses"
)

# 4. 工具执行指标
TOOL_EXECUTION_COUNT = get_or_create_metric(
    Counter, "sparkle_tool_executions_total", "Total number of tool executions", ["tool_name", "status"]
)

# 5. 系统指标
ACTIVE_SESSIONS = get_or_create_metric(Gauge, "sparkle_active_sessions_total", "Total number of active chat sessions")

SESSION_ID_FALLBACK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_session_id_fallback_total",
    "Total StreamChat responses that required a backend-generated session_id fallback",
    ["source"],
)

KNOWLEDGE_NODE_UPDATES = get_or_create_metric(
    Counter,
    "sparkle_knowledge_node_updates_total",
    "Total number of knowledge node updates",
    ["reason"],  # Removed user_id
)

RAG_RETRIEVAL_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_rag_retrieval_seconds",
    "RAG retrieval latency",
    ["source", "stage"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
)

RETRIEVAL_TIMEOUT_TOTAL = get_or_create_metric(
    Counter, "sparkle_retrieval_timeout_total", "Total retrieval timeouts", ["source", "stage"]
)

RETRIEVAL_ERROR_TOTAL = get_or_create_metric(
    Counter, "sparkle_retrieval_error_total", "Total retrieval errors", ["source", "stage"]
)

ACTIVE_WEBSOCKET_CONNECTIONS = get_or_create_metric(
    Gauge, "sparkle_websocket_connections", "Number of active WebSocket connections"
)

OUTBOX_PENDING_EVENTS = get_or_create_metric(
    Gauge, "sparkle_outbox_pending_events", "Number of pending events in the outbox table"
)

INTERVENTION_DELIVERY_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_intervention_delivery_total",
    "Intervention delivery attempts by channel and result",
    ["channel", "result"],
)

INTERVENTION_PUSH_HISTORY_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_intervention_push_history_total",
    "Intervention push history writes",
    ["status"],
)

INTERVENTION_PARAMETER_COMPILATION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_intervention_parameter_compilation_total",
    "Breakpoint 5 parameter compilation results for intervention delivery",
    ["result"],
)

SAFE_EXPERIMENT_TRANSITIONS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_safe_experiment_transitions_total",
    "Safe experiment lifecycle transitions",
    ["from_status", "to_status", "result"],
)

SAFE_EXPERIMENT_EPISODES_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_safe_experiment_episodes_total",
    "Safe experiment episodes recorded",
    ["experiment_status", "risk_level"],
)

SAFE_EXPERIMENT_GUARDRAIL_VIOLATIONS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_safe_experiment_guardrail_violations_total",
    "Safe experiment guardrail violations by guardrail and action",
    ["guardrail", "action"],
)

SAFE_EXPERIMENT_PROMOTION_CANDIDATES = get_or_create_metric(
    Gauge,
    "sparkle_safe_experiment_promotion_candidates",
    "Current safe experiment promotion candidates pending approval",
)

SAFE_EXPERIMENT_BANDIT_BLOCK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_safe_experiment_bandit_block_total",
    "Safe bandit selections blocked by high-risk or opt-out conditions",
    ["reason"],
)

SRL_EVENT_PUBLISHED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_srl_event_published_total",
    "Total SRL transition events published by trigger and mode",
    ["trigger_event_type", "mode"],
)

SRL_EVENT_CONSUMED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_srl_event_consumed_total",
    "Total SRL transition events consumed by trigger and status",
    ["trigger_event_type", "status"],
)

SRL_EVENT_LAG_P95 = get_or_create_metric(
    Gauge,
    "sparkle_srl_event_lag_p95_seconds",
    "Latest p95 lag for SRL transition events in seconds",
)

SRL_PHASE_TRANSITION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_srl_phase_transition_total",
    "SRL phase transitions by from/to phase and source",
    ["from_phase", "to_phase", "source"],
)

SRL_PHASE_UNKNOWN_RATE = get_or_create_metric(
    Gauge,
    "sparkle_srl_phase_unknown_rate",
    "Latest rate of users in UNKNOWN SRL phase",
)

SRL_SCAFFOLDING_ADJUSTED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_srl_scaffolding_adjusted_total",
    "Scaffolding support adjustments from SRL phase hints",
    ["phase", "mode", "applied"],
)

MARKETPLACE_ADOPTIONS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_marketplace_adoptions_total",
    "Skill and DomainPack marketplace adoption transitions",
    ["asset_type", "status"],
)

MARKETPLACE_PRIVACY_REJECTIONS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_marketplace_privacy_rejections_total",
    "Marketplace assets rejected before listing because PII was detected",
    ["asset_type"],
)

MARKETPLACE_AUTO_DEPRECATIONS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_marketplace_auto_deprecations_total",
    "Marketplace assets automatically deprecated or flagged by quality guardrails",
    ["asset_type", "reason"],
)

MARKETPLACE_QUALITY_SCORE = get_or_create_metric(
    Gauge,
    "sparkle_marketplace_quality_score",
    "Latest outcome-weighted marketplace quality score by asset class and domain",
    ["asset_type", "domain", "status"],
)

METACOG_BIAS_UPDATED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_bias_updated_total",
    "Metacognition snapshot refresh results",
    ["result"],
)

METACOG_SAMPLE_BELOW_THRESHOLD_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_sample_below_threshold_total",
    "Dimensions filtered because sample size is below threshold",
    ["dim"],
)

METACOG_PROCESS_SCAFFOLD_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_process_scaffold_total",
    "Process scaffolding trigger and skip reasons",
    ["status", "reason"],
)

METACOG_DIAGNOSTIC_WORD_HIT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_diagnostic_word_hit_total",
    "Diagnostic label hits detected in metacognition text",
    ["source"],
)

METACOG_DASHBOARD_VIEW_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_dashboard_view_total",
    "Dashboard payload exposures for the metacognition panel",
    ["visibility"],
)

METACOG_SCAFFOLDING_COMBINE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_metacognition_scaffolding_combine_total",
    "Final combine states for SRL and metacognition scaffolding deltas",
    ["combine_state"],
)

SRL_ROUTER_ZERO_HIT = get_or_create_metric(
    Gauge,
    "sparkle_srl_router_zero_hit",
    "Stage 29 Rule AN router zero-hit status",
)

SRL_TRACKER_LOCK_CONTENTION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_srl_tracker_lock_contention_total",
    "SRL tracker lock contention count",
    ["mode"],
)

SRL_DLQ_SIZE = get_or_create_metric(
    Gauge,
    "sparkle_srl_dlq_size",
    "Current SRL DLQ size",
)

SPARKLE_PROMPT_FIELD_RENDER_COVERAGE_RATIO = get_or_create_metric(
    Gauge,
    "sparkle_prompt_field_render_coverage_ratio",
    "Prompt field render coverage ratio for normalized user-context fields",
)

SOURCE_STATE_ENCODER_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_source_state_encoder_seconds",
    "Source-state encoder latency in seconds",
    buckets=[0.001, 0.003, 0.005, 0.008, 0.01, 0.015, 0.03, 0.05],
)

ROUTING_OUTCOME_BACKFILL_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_routing_outcome_backfill_seconds",
    "Routing decision outcome backfill latency in seconds",
    ["outcome"],
    buckets=[1, 5, 15, 30, 60, 120, 300, 600, 1800],
)

AURORA_ROUTING_SIGNAL_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_routing_signal_total",
    "DualCore routing decisions persisted as SGW passive signals",
    ["mode", "dominant_signal"],
)

AURORA_ROUTING_OUTCOME_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_routing_outcome_total",
    "Delayed DualCore routing outcome evaluations",
    ["mode", "success", "reason"],
)

AURORA_CORE_SESSION_EVENT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_core_session_event_total",
    "Aurora Core Session lifecycle events",
    ["event", "status"],
)

AURORA_RETURNING_CONTEXT_TIER_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_returning_context_tier_total",
    "Returning context tiers attached to a user turn",
    ["tier"],
)

AURORA_CORRECTION_TO_STATE_CHANGE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_correction_to_state_change_total",
    "Aurora corrections that produced state/profile changes",
    ["surface", "action", "changed"],
)

AURORA_CORRECTION_FAILURE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_aurora_correction_failure_total",
    "Aurora correction processing failures by surface and reason",
    ["surface", "reason"],
)

BAYESIAN_RECOMMENDATION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_bayesian_recommendation_total",
    "Bayesian routing recommendations by event and mode",
    ["event", "mode"],
)

BAYESIAN_SHADOW_DIVERGENCE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_bayesian_shadow_divergence_total",
    "Bayesian shadow divergences from fallback routing",
    ["mode"],
)

# 5b. Proto v2 Migration Metrics
PROTO_FIELD_READ_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_proto_field_read_total",
    "Total protocol field reads by source during v1/v2 migration",
    ["service", "field", "source"],
)

PROTO_DUAL_WRITE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_proto_dual_write_total",
    "Total dual-write operations for legacy compatibility fields",
    ["service", "field"],
)

PROTO_ERROR_CODE_FALLBACK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_proto_error_code_fallback_total",
    "Total error code fallback operations during v1/v2 migration",
    ["service", "direction"],
)

# 6. Response Feedback & Bandit
RESPONSE_FEEDBACK_INGESTED = get_or_create_metric(
    Counter,
    "sparkle_response_feedback_ingested_total",
    "Total response feedback ingested",
    ["feedback_type"],  # values: up, down
)

RESPONSE_FEEDBACK_DEDUPE_TOTAL = get_or_create_metric(
    Counter, "sparkle_response_feedback_dedup_total", "Total response feedback deduplicated"
)

PROMPT_BANDIT_UPDATES_TOTAL = get_or_create_metric(
    Counter, "sparkle_prompt_bandit_updates_total", "Total prompt bandit updates", ["workflow_id"]
)

PROMPT_BANDIT_STATE_MISSING_TOTAL = get_or_create_metric(
    Counter, "sparkle_prompt_bandit_state_missing_total", "Total prompt bandit state misses", ["workflow_id"]
)

FEEDBACK_TO_EFFECT_SECONDS = get_or_create_metric(
    Histogram,
    "sparkle_feedback_to_effect_seconds",
    "Time from feedback ingestion to prompt selection effect",
    ["workflow_id", "prompt_version"],
    buckets=[60, 300, 900, 1800, 3600, 14400, 86400],
)

SESSION_FEEDBACK_DETECTED_TOTAL = get_or_create_metric(
    Counter, "sparkle_session_feedback_detected_total", "Total detected in-session feedback signals", ["signal_type"]
)

SESSION_FEEDBACK_APPLIED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_session_feedback_applied_total",
    "Total in-session feedback signals that changed the current-turn strategy",
    ["signal_type"],
)

SESSION_FEEDBACK_VISIBLE_HINT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_session_feedback_visible_hint_total",
    "Total visible session adaptation hints surfaced to the user",
    ["signal_type"],
)

SESSION_FEEDBACK_IGNORED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_session_feedback_ignored_total",
    "Total in-session feedback signals ignored or bypassed",
    ["reason"],
)

SESSION_FEEDBACK_CONFIDENCE_BUCKET = get_or_create_metric(
    Counter,
    "sparkle_session_feedback_confidence_bucket",
    "Confidence buckets for detected in-session feedback signals",
    ["signal_type", "bucket"],
)

PHASE_A_DECISION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_phase_a_decision_total",
    "Phase A planning readiness decisions by action",
    ["action"],
)

PHASE_A_GAP_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_phase_a_gap_total",
    "Phase A missing planning gaps by gap id",
    ["gap_id"],
)

PHASE_A_CONTRADICTION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_phase_a_contradiction_total",
    "Phase A contradiction frequency by id and severity",
    ["contradiction_id", "severity"],
)

PHASE_A_PLANNING_LIKE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_phase_a_planning_like_total",
    "Phase A planning-like turn evaluations by detection source",
    ["source"],
)

AGENT_PERFORMANCE_RECORDED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_agent_performance_recorded_total",
    "Total recorded agent performance samples",
    ["agent_id", "success"],
)

AGENT_FEEDBACK_LINKED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_agent_feedback_linked_total",
    "Total response feedback events linked back to participating agents",
    ["feedback_type"],
)

AGENT_ROUTING_QUALITY_PROMPT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_agent_routing_quality_prompt_total",
    "Total routing prompts enriched with agent quality summaries",
    ["layer"],
)

AGENT_COLLAB_DECISION_TOTAL = get_or_create_metric(
    Counter, "sparkle_agent_collab_decision_total", "Total collaboration decisions by source", ["source", "intent_type"]
)

AGENT_COMBINATION_EXPLORATION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_agent_combination_exploration_total",
    "Total exploratory agent-combination selections",
    ["intent_type"],
)

LLM_ROUTER_SELECTION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_llm_router_selection_total",
    "Total model-routing selections made by the unified LLM router",
    ["agent_role", "model_key", "provider", "tier", "task_type", "complexity", "fallback"],
)

LLM_ROUTER_ESTIMATED_COST_PER_1K = get_or_create_metric(
    Histogram,
    "sparkle_llm_router_estimated_cost_per_1k",
    "Estimated cost-per-1k tokens for router selections",
    ["agent_role", "provider", "tier"],
    buckets=[0.0, 0.0001, 0.0005, 0.001, 0.002, 0.005, 0.01],
)

RUN_LEDGER_EVENT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_run_ledger_event_total",
    "Total unified run-ledger events recorded",
    ["event_type", "workflow_stage"],
)

RUN_LEDGER_REVIEW_SCORE = get_or_create_metric(
    Histogram,
    "sparkle_run_ledger_review_score",
    "Review scores captured by the unified run ledger",
    ["target_type", "decision"],
    buckets=[0.0, 0.25, 0.5, 0.65, 0.75, 0.85, 0.95, 1.0],
)

RUN_LEDGER_FEEDBACK_EFFECT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_run_ledger_feedback_effect_total",
    "Total feedback-to-strategy effects captured by the unified run ledger",
    ["effect_target", "status"],
)

PRODUCT_LOOP_EVENT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_product_loop_event_total",
    "User-impact product loop events by loop, surface, outcome, and reason",
    ["loop", "surface", "outcome", "reason"],
)

PRODUCT_LOOP_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_product_loop_latency_seconds",
    "Latency for user-impact product loop operations",
    ["loop", "surface", "outcome"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0],
)

PRODUCT_LOOP_ITEMS = get_or_create_metric(
    Histogram,
    "sparkle_product_loop_items",
    "Items returned or affected by user-impact product loop operations",
    ["loop", "surface"],
    buckets=[0, 1, 3, 5, 10, 20, 50],
)


def _product_loop_label(value: str | None, default: str = "unknown") -> str:
    """Keep product-loop labels bounded and Prometheus-friendly."""
    normalized = (value or default).strip().lower().replace(" ", "_").replace("-", "_")
    normalized = "".join(char for char in normalized if char.isalnum() or char == "_")
    return (normalized or default)[:64]


def record_product_loop_event(
    loop: str,
    surface: str,
    outcome: str,
    reason: str = "none",
) -> None:
    """Record a best-effort user-impact event without affecting request handling."""
    try:
        PRODUCT_LOOP_EVENT_TOTAL.labels(
            loop=_product_loop_label(loop),
            surface=_product_loop_label(surface),
            outcome=_product_loop_label(outcome),
            reason=_product_loop_label(reason, "none"),
        ).inc()
    except Exception as exc:  # pragma: no cover - metrics must never break product flows
        logger.debug(f"Failed to record product-loop event metric: {exc}")


def observe_product_loop_latency(loop: str, surface: str, outcome: str, duration_seconds: float) -> None:
    """Observe a best-effort latency sample for an operational product loop."""
    try:
        PRODUCT_LOOP_LATENCY.labels(
            loop=_product_loop_label(loop),
            surface=_product_loop_label(surface),
            outcome=_product_loop_label(outcome),
        ).observe(max(0.0, float(duration_seconds)))
    except Exception as exc:  # pragma: no cover - metrics must never break product flows
        logger.debug(f"Failed to record product-loop latency metric: {exc}")


def observe_product_loop_items(loop: str, surface: str, count: int) -> None:
    """Observe a best-effort item-count sample for an operational product loop."""
    try:
        PRODUCT_LOOP_ITEMS.labels(
            loop=_product_loop_label(loop),
            surface=_product_loop_label(surface),
        ).observe(max(0, int(count)))
    except Exception as exc:  # pragma: no cover - metrics must never break product flows
        logger.debug(f"Failed to record product-loop item metric: {exc}")


# 装饰器：用于测量函数执行时间并记录指标
def track_latency(module, method):
    """Decorator to track function execution latency and record metrics."""

    def decorator(func):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            start_time = time.time()
            span = trace.get_current_span()
            trace_id = format(span.get_span_context().trace_id, "032x") if span else "n/a"

            try:
                result = await func(*args, **kwargs)
                REQUEST_COUNT.labels(module=module, method=method, status="success").inc()
                return result
            except Exception as e:
                # Log with TraceID for correlation
                logger.error(f"[TraceID: {trace_id}] Error in {module}.{method}: {e}")
                REQUEST_COUNT.labels(module=module, method=method, status="error").inc()
                raise
            finally:
                latency = time.time() - start_time
                REQUEST_LATENCY.labels(module=module, method=method).observe(latency)

        @wraps(func)
        def sync_wrapper(*args, **kwargs):
            start_time = time.time()

            try:
                result = func(*args, **kwargs)
                REQUEST_COUNT.labels(module=module, method=method, status="success").inc()
                return result
            except Exception as e:
                logger.error(f"Error in {module}.{method}: {e}")
                REQUEST_COUNT.labels(module=module, method=method, status="error").inc()
                raise
            finally:
                latency = time.time() - start_time
                REQUEST_LATENCY.labels(module=module, method=method).observe(latency)

        # Return async wrapper if func is async, else sync wrapper
        if iscoroutinefunction(func):
            return async_wrapper
        else:
            return sync_wrapper

    return decorator


# ============ Phase 3: Circuit Breaker & Collaboration Metrics ============

LANGGRAPH_PLANNING_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_langgraph_planning_total",
    "Total number of LangGraph planning operations",
    ["collaboration_mode", "agents_count"],
)

LANGGRAPH_PLANNING_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_langgraph_planning_latency_seconds",
    "LangGraph planning latency in seconds",
    ["collaboration_mode"],
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0],
)

CIRCUIT_BREAKER_TRIPS = get_or_create_metric(
    Counter, "sparkle_circuit_breaker_trips_total", "Total number of circuit breaker trips", ["circuit_name"]
)

CIRCUIT_BREAKER_RESETS = get_or_create_metric(
    Counter, "sparkle_circuit_breaker_resets_total", "Total number of circuit breaker resets", ["circuit_name"]
)

COLLABORATION_SUCCESS = get_or_create_metric(
    Counter,
    "sparkle_collaboration_total",
    "Total number of collaboration operations",
    ["workflow_type", "agents_used", "outcome"],
)

COLLABORATION_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_collaboration_latency_seconds",
    "Collaboration latency in seconds",
    ["workflow_type"],
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

EXPERT_SELECTED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_expert_selected_total",
    "Total expert selections by strategy and source",
    ["expert_id", "strategy", "entry_source"],
)

EXPERT_INVOKED_TOTAL = get_or_create_metric(
    Counter, "sparkle_expert_invoked_total", "Total expert invocations", ["expert_id", "workflow_id"]
)

EXPERT_FALLBACK_TOTAL = get_or_create_metric(
    Counter, "sparkle_expert_fallback_total", "Total expert fallbacks", ["reason", "from_mode"]
)

EXPERT_OVERRIDDEN_TOTAL = get_or_create_metric(
    Counter, "sparkle_expert_overridden_total", "Total explicit expert overrides", ["requested_expert", "used_expert"]
)

USER_FEEDBACK_BOUND_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_user_feedback_bound_total",
    "Total feedback events bound to expert routing context",
    ["workflow_id"],
)

# ============ Strategy Optimization Metrics ============

ADAPTIVE_ROUTING_ADJUSTMENTS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_adaptive_routing_adjustments_total",
    "Adaptive routing adjustments by trigger and mode change",
    ["action", "trigger", "from_mode", "to_mode"],
)

ROUTING_SUMMARY_CONTEXT_TOTAL = get_or_create_metric(
    Counter, "sparkle_routing_summary_context_total", "Summary context usage in routing", ["phase"]
)

AURORA_STAGE33_FALLBACK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_stage33_fallback_total",
    "Stage33 fallbacks by feature and reason",
    ["feature", "reason"],
)

JOURNEY_EVENT_CONSUMER_ERROR_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_journey_event_consumer_error_total",
    "Stage34 journey consumer failures by consumer and event",
    ["consumer", "event"],
)

ERROR_REPLAN_BRIDGE_ERROR_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_error_replan_bridge_error_total",
    "Stage34 ErrorReplanBridge classified failures by category and mode",
    ["category", "mode"],
)

ERROR_REPLAN_BRIDGE_EVALUATED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_error_replan_bridge_evaluated_total",
    "Stage38 ErrorReplanBridge evaluations by mode",
    ["mode"],
)

ERROR_REPLAN_BRIDGE_TRIGGERED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_error_replan_bridge_triggered_total",
    "Stage38 ErrorReplanBridge triggers by mode",
    ["mode"],
)

ERROR_REPLAN_BRIDGE_BLOCKED_BY_GATE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_error_replan_bridge_blocked_by_gate_total",
    "Stage38 ErrorReplanBridge blocks by gate and mode",
    ["gate", "mode"],
)

FSM_CONTEXT_SIZE_BYTES = get_or_create_metric(
    Gauge,
    "sparkle_fsm_context_size_bytes",
    "Latest FSM context_data payload size in bytes",
)

FSM_CONTEXT_EVICTION_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_fsm_context_eviction_total",
    "Total FSM context_data evictions triggered by Stage38 guardrails",
)

CALENDAR_FALLBACK_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_calendar_fallback_total",
    "Stage40 calendar prompt-path fallbacks by reason and mode",
    ["reason", "mode"],
)

KILL_SWITCH_MODE = get_or_create_metric(
    Gauge,
    "sparkle_kill_switch_mode",
    "Kill switch mode gauge by stage and feature",
    ["stage", "feature"],
)

DOCUMENT_CONTEXT_CHUNKS_INJECTED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_document_context_chunks_injected_total",
    "Total document-context chunks injected into prompts",
)

DOCUMENT_CONTEXT_TOKENS_USED = get_or_create_metric(
    Histogram,
    "sparkle_document_context_tokens_used",
    "Document-context prompt tokens used per injected turn",
    buckets=[0, 64, 128, 256, 512, 768, 1024, 1536, 2048, 3072, 4096],
)

DOCUMENT_CONTEXT_CACHE_HIT_RATIO = get_or_create_metric(
    Gauge,
    "sparkle_document_context_cache_hit_ratio",
    "Latest document-context cache hit ratio",
)

LLM_SAFETY_BYPASS_TOTAL = get_or_create_metric(
    Counter,
    "llm_safety_bypass_total",
    "Total LLM safety bypass events by surface",
    ["surface"],
)

RESPONSE_FALLBACK_GENERATED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_response_fallback_generated_total",
    "Fallback responses generated to avoid empty output",
    ["source"],
)

# ============ Phase 4: Preference Inference Metrics ============

PREFERENCE_INFERENCE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_preference_inference_total",
    "Total number of preference inferences from feedback",
    ["preference_key", "direction", "source"],  # source: feedback, behavior
)

PREFERENCE_INFERENCE_CONFIDENCE = get_or_create_metric(
    Gauge,
    "sparkle_preference_inference_confidence",
    "Current confidence level for inferred preferences",
    ["preference_key"],
)

PREFERENCE_DECAY_APPLIED_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_preference_decay_applied_total",
    "Total number of preference decay operations",
    ["preference_key", "action"],  # action: decay, reset
)

# ============ Phase 4: Preference Event Latency Metrics ============

PREFERENCE_EVENT_E2E_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_preference_event_e2e_latency_seconds",
    "End-to-end latency from preference update to cache invalidation",
    ["event_type", "source"],
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

PREFERENCE_EVENT_CONSUME_LAG = get_or_create_metric(
    Gauge,
    "sparkle_preference_event_consume_lag_seconds",
    "Time lag between event publish and consumer processing",
    ["consumer_group"],
)

PREFERENCE_EVENT_STREAM_LENGTH = get_or_create_metric(
    Gauge, "sparkle_preference_event_stream_length", "Number of pending events in Redis Stream", ["stream_key"]
)

CACHE_INVALIDATION_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_cache_invalidation_latency_seconds",
    "Time from cache invalidation call to completion",
    ["cache_type"],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5],
)

PREFERENCE_EVENT_ERRORS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_preference_event_errors_total",
    "Total preference event processing errors",
    ["error_type", "consumer_group"],
)

# ============ Phase 3: Event Bus Health Metrics ============

EVENT_BUS_DLQ_MESSAGES = get_or_create_metric(
    Gauge, "sparkle_event_bus_dlq_messages", "Number of messages in the Dead Letter Queue", ["stream"]
)

EVENT_BUS_CONSUMER_LAG_MESSAGES = get_or_create_metric(
    Gauge,
    "sparkle_event_bus_consumer_lag_messages",
    "Number of pending messages behind the stream head for a consumer group",
    ["stream", "consumer_group"],
)

EVENT_BUS_CONSUMER_LAG_SECONDS = get_or_create_metric(
    Gauge,
    "sparkle_event_bus_consumer_lag_seconds",
    "Time lag in seconds between stream head and consumer group position",
    ["stream", "consumer_group"],
)

EVENT_BUS_PUBLISH_RETRIES_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_event_bus_publish_retries_total",
    "Event bus publish retry attempts by event type",
    ["event_type"],
)

EVENT_BUS_DLQ_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_event_bus_dlq_total",
    "Total DLQ writes by event type",
    ["event_type"],
)

EVENT_BUS_DLQ_DEPTH = get_or_create_metric(
    Gauge,
    "sparkle_event_bus_dlq_depth",
    "Current DLQ depth (pending entries) by stream",
    ["stream"],
)

EVENT_BUS_CONSUMER_FAILURE_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_event_bus_consumer_failure_total",
    "Total consumer callback failures by consumer",
    ["consumer"],
)

SPARKLE_SKILL_COUNT_PER_USER = get_or_create_metric(
    Histogram,
    "sparkle_skill_count_per_user",
    "Observed skill counts per user against the Stage 21 cap",
    buckets=[0, 1, 3, 5, 10, 20, 30, 40, 50],
)

SPARKLE_SKILL_EXTRACT_DRAFT_ACCEPT_RATE = get_or_create_metric(
    Gauge,
    "sparkle_skill_extract_draft_accept_rate",
    "Acceptance ratio for Stage 21 skill drafts",
)

SPARKLE_SKILL_SELECTION_ACTIVATION_RATE = get_or_create_metric(
    Histogram,
    "sparkle_skill_selection_activation_rate",
    "Distribution of how many skills activate per routing turn",
    buckets=[0, 1, 2, 3],
)

SPARKLE_SKILL_SHARE_PIPELINE_LATENCY_SECONDS = get_or_create_metric(
    Histogram,
    "sparkle_skill_share_pipeline_latency_seconds",
    "End-to-end latency for the Stage 21 skill share pipeline",
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0],
)

# ============ FV-05: Privacy Community Intelligence Metrics ============

COMMUNITY_PRIVACY_AGGREGATES_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_community_privacy_aggregates_total",
    "Privacy-preserving community aggregates by stat and result",
    ["stat_name", "privacy_tier", "result"],
)

COMMUNITY_PRIVACY_BUDGET_SPENT_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_community_privacy_budget_spent_total",
    "Differential privacy epsilon spent for community aggregate queries",
    ["query_type", "status"],
)

COMMUNITY_PRIVACY_BUDGET_REMAINING = get_or_create_metric(
    Gauge,
    "sparkle_community_privacy_budget_remaining",
    "Remaining epsilon budget for community aggregate query subjects",
    ["budget_subject", "query_type"],
)

COMMUNITY_PRIVACY_COHORT_SIZE = get_or_create_metric(
    Histogram,
    "sparkle_community_privacy_cohort_size",
    "Cohort sizes seen by the privacy-preserving community engine",
    ["stat_name", "privacy_tier"],
    buckets=[0, 1, 3, 5, 10, 15, 25, 50, 100, 250],
)

# ============ FV-22: Community Resource Quality Metrics ============

COMMUNITY_RESOURCE_QUALITY_SCORE = get_or_create_metric(
    Histogram,
    "sparkle_community_resource_quality_score",
    "Quality score distribution of community shared resources",
    ["resource_type"],
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

COMMUNITY_RESOURCE_MISLEADING_FLAGS_TOTAL = get_or_create_metric(
    Counter,
    "sparkle_community_resource_misleading_flags_total",
    "Total misleading flags raised on community resources",
    ["resource_id"],
)

# ============ Phase 6: Performance SLO Metrics ============

GALAXY_E2E_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_galaxy_e2e_latency_seconds",
    "End-to-end Galaxy service request latency",
    ["operation"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0],
)

TASK_GENERATION_E2E_LATENCY = get_or_create_metric(
    Histogram,
    "sparkle_task_generation_e2e_seconds",
    "End-to-end task generation latency (from request to task cards ready)",
    ["source"],
    buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0],
)
